package org.ipay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class T_check_exception implements Serializable {
    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : ID
     */
    private BigDecimal ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : ORDER_NO
     */
    private String ORDER_NO;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : REFUND_NO
     */
    private String REFUND_NO;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : BILL_ID
     */
    private BigDecimal BILL_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHANNEL_ID
     */
    private BigDecimal CHANNEL_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : BUSINESS_TYPE
     */
    private String BUSINESS_TYPE;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : MERCHANT_ID
     */
    private BigDecimal MERCHANT_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : SHOP_ID
     */
    private BigDecimal SHOP_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : ORG_ID
     */
    private BigDecimal ORG_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : TOP_ORG_ID
     */
    private BigDecimal TOP_ORG_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : PAY_AMOUNT
     */
    private BigDecimal PAY_AMOUNT;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : ORDER_TRADE_TIME
     */
    private Date ORDER_TRADE_TIME;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : ORDER_PAY_TYPE
     */
    private String ORDER_PAY_TYPE;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : ORDER_STATUS
     */
    private String ORDER_STATUS;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHANNEL_ORDER_NO
     */
    private String CHANNEL_ORDER_NO;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHANNEL_AMOUNT
     */
    private BigDecimal CHANNEL_AMOUNT;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHANNEL_DISCOUNT_AMOUNT
     */
    private BigDecimal CHANNEL_DISCOUNT_AMOUNT;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHANNEL_EXPIRE_TIME
     */
    private Date CHANNEL_EXPIRE_TIME;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHANNEL_PAY_TYPE
     */
    private String CHANNEL_PAY_TYPE;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHECK_DATE
     */
    private String CHECK_DATE;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CHECK_STATUS
     */
    private String CHECK_STATUS;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : DEAL_WAY
     */
    private String DEAL_WAY;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : DEAL_STATUS
     */
    private String DEAL_STATUS;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : BELONG_MERCHANT_ID
     */
    private BigDecimal BELONG_MERCHANT_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : BELONG_SHOP_ID
     */
    private BigDecimal BELONG_SHOP_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : BELONG_STAFF_ID
     */
    private BigDecimal BELONG_STAFF_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CREDENTIALS_PATH
     */
    private String CREDENTIALS_PATH;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : DEAL_REASON
     */
    private String DEAL_REASON;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : DEAL_PERSON_ID
     */
    private BigDecimal DEAL_PERSON_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : DEAL_TIME
     */
    private Date DEAL_TIME;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CREATED_TIME
     */
    private Date CREATED_TIME;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : CREATED_ID
     */
    private BigDecimal CREATED_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : UPDATED_TIME
     */
    private Date UPDATED_TIME;

    /**
     * 表 : IPAY_CORE_TEST.T_CHECK_EXCEPTION
     * 对应字段 : UPDATED_ID
     */
    private BigDecimal UPDATED_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IPAY_CORE_TEST.T_CHECK_EXCEPTION
     *
     * @MBG Generated Mon Aug 07 19:43:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.ID：null
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.ORDER_NO：null
     */
    public String getORDER_NO() {
        return ORDER_NO;
    }

    /**
     * set method 
     *
     * @param ORDER_NO  null
     */
    public void setORDER_NO(String ORDER_NO) {
        this.ORDER_NO = ORDER_NO == null ? null : ORDER_NO.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.REFUND_NO：null
     */
    public String getREFUND_NO() {
        return REFUND_NO;
    }

    /**
     * set method 
     *
     * @param REFUND_NO  null
     */
    public void setREFUND_NO(String REFUND_NO) {
        this.REFUND_NO = REFUND_NO == null ? null : REFUND_NO.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.BILL_ID：null
     */
    public BigDecimal getBILL_ID() {
        return BILL_ID;
    }

    /**
     * set method 
     *
     * @param BILL_ID  null
     */
    public void setBILL_ID(BigDecimal BILL_ID) {
        this.BILL_ID = BILL_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHANNEL_ID：null
     */
    public BigDecimal getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    /**
     * set method 
     *
     * @param CHANNEL_ID  null
     */
    public void setCHANNEL_ID(BigDecimal CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.BUSINESS_TYPE：null
     */
    public String getBUSINESS_TYPE() {
        return BUSINESS_TYPE;
    }

    /**
     * set method 
     *
     * @param BUSINESS_TYPE  null
     */
    public void setBUSINESS_TYPE(String BUSINESS_TYPE) {
        this.BUSINESS_TYPE = BUSINESS_TYPE == null ? null : BUSINESS_TYPE.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.MERCHANT_ID：null
     */
    public BigDecimal getMERCHANT_ID() {
        return MERCHANT_ID;
    }

    /**
     * set method 
     *
     * @param MERCHANT_ID  null
     */
    public void setMERCHANT_ID(BigDecimal MERCHANT_ID) {
        this.MERCHANT_ID = MERCHANT_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.SHOP_ID：null
     */
    public BigDecimal getSHOP_ID() {
        return SHOP_ID;
    }

    /**
     * set method 
     *
     * @param SHOP_ID  null
     */
    public void setSHOP_ID(BigDecimal SHOP_ID) {
        this.SHOP_ID = SHOP_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.ORG_ID：null
     */
    public BigDecimal getORG_ID() {
        return ORG_ID;
    }

    /**
     * set method 
     *
     * @param ORG_ID  null
     */
    public void setORG_ID(BigDecimal ORG_ID) {
        this.ORG_ID = ORG_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.TOP_ORG_ID：null
     */
    public BigDecimal getTOP_ORG_ID() {
        return TOP_ORG_ID;
    }

    /**
     * set method 
     *
     * @param TOP_ORG_ID  null
     */
    public void setTOP_ORG_ID(BigDecimal TOP_ORG_ID) {
        this.TOP_ORG_ID = TOP_ORG_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.PAY_AMOUNT：null
     */
    public BigDecimal getPAY_AMOUNT() {
        return PAY_AMOUNT;
    }

    /**
     * set method 
     *
     * @param PAY_AMOUNT  null
     */
    public void setPAY_AMOUNT(BigDecimal PAY_AMOUNT) {
        this.PAY_AMOUNT = PAY_AMOUNT;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.ORDER_TRADE_TIME：null
     */
    public Date getORDER_TRADE_TIME() {
        return ORDER_TRADE_TIME;
    }

    /**
     * set method 
     *
     * @param ORDER_TRADE_TIME  null
     */
    public void setORDER_TRADE_TIME(Date ORDER_TRADE_TIME) {
        this.ORDER_TRADE_TIME = ORDER_TRADE_TIME;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.ORDER_PAY_TYPE：null
     */
    public String getORDER_PAY_TYPE() {
        return ORDER_PAY_TYPE;
    }

    /**
     * set method 
     *
     * @param ORDER_PAY_TYPE  null
     */
    public void setORDER_PAY_TYPE(String ORDER_PAY_TYPE) {
        this.ORDER_PAY_TYPE = ORDER_PAY_TYPE == null ? null : ORDER_PAY_TYPE.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.ORDER_STATUS：null
     */
    public String getORDER_STATUS() {
        return ORDER_STATUS;
    }

    /**
     * set method 
     *
     * @param ORDER_STATUS  null
     */
    public void setORDER_STATUS(String ORDER_STATUS) {
        this.ORDER_STATUS = ORDER_STATUS == null ? null : ORDER_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHANNEL_ORDER_NO：null
     */
    public String getCHANNEL_ORDER_NO() {
        return CHANNEL_ORDER_NO;
    }

    /**
     * set method 
     *
     * @param CHANNEL_ORDER_NO  null
     */
    public void setCHANNEL_ORDER_NO(String CHANNEL_ORDER_NO) {
        this.CHANNEL_ORDER_NO = CHANNEL_ORDER_NO == null ? null : CHANNEL_ORDER_NO.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHANNEL_AMOUNT：null
     */
    public BigDecimal getCHANNEL_AMOUNT() {
        return CHANNEL_AMOUNT;
    }

    /**
     * set method 
     *
     * @param CHANNEL_AMOUNT  null
     */
    public void setCHANNEL_AMOUNT(BigDecimal CHANNEL_AMOUNT) {
        this.CHANNEL_AMOUNT = CHANNEL_AMOUNT;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHANNEL_DISCOUNT_AMOUNT：null
     */
    public BigDecimal getCHANNEL_DISCOUNT_AMOUNT() {
        return CHANNEL_DISCOUNT_AMOUNT;
    }

    /**
     * set method 
     *
     * @param CHANNEL_DISCOUNT_AMOUNT  null
     */
    public void setCHANNEL_DISCOUNT_AMOUNT(BigDecimal CHANNEL_DISCOUNT_AMOUNT) {
        this.CHANNEL_DISCOUNT_AMOUNT = CHANNEL_DISCOUNT_AMOUNT;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHANNEL_EXPIRE_TIME：null
     */
    public Date getCHANNEL_EXPIRE_TIME() {
        return CHANNEL_EXPIRE_TIME;
    }

    /**
     * set method 
     *
     * @param CHANNEL_EXPIRE_TIME  null
     */
    public void setCHANNEL_EXPIRE_TIME(Date CHANNEL_EXPIRE_TIME) {
        this.CHANNEL_EXPIRE_TIME = CHANNEL_EXPIRE_TIME;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHANNEL_PAY_TYPE：null
     */
    public String getCHANNEL_PAY_TYPE() {
        return CHANNEL_PAY_TYPE;
    }

    /**
     * set method 
     *
     * @param CHANNEL_PAY_TYPE  null
     */
    public void setCHANNEL_PAY_TYPE(String CHANNEL_PAY_TYPE) {
        this.CHANNEL_PAY_TYPE = CHANNEL_PAY_TYPE == null ? null : CHANNEL_PAY_TYPE.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHECK_DATE：null
     */
    public String getCHECK_DATE() {
        return CHECK_DATE;
    }

    /**
     * set method 
     *
     * @param CHECK_DATE  null
     */
    public void setCHECK_DATE(String CHECK_DATE) {
        this.CHECK_DATE = CHECK_DATE == null ? null : CHECK_DATE.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CHECK_STATUS：null
     */
    public String getCHECK_STATUS() {
        return CHECK_STATUS;
    }

    /**
     * set method 
     *
     * @param CHECK_STATUS  null
     */
    public void setCHECK_STATUS(String CHECK_STATUS) {
        this.CHECK_STATUS = CHECK_STATUS == null ? null : CHECK_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.DEAL_WAY：null
     */
    public String getDEAL_WAY() {
        return DEAL_WAY;
    }

    /**
     * set method 
     *
     * @param DEAL_WAY  null
     */
    public void setDEAL_WAY(String DEAL_WAY) {
        this.DEAL_WAY = DEAL_WAY == null ? null : DEAL_WAY.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.DEAL_STATUS：null
     */
    public String getDEAL_STATUS() {
        return DEAL_STATUS;
    }

    /**
     * set method 
     *
     * @param DEAL_STATUS  null
     */
    public void setDEAL_STATUS(String DEAL_STATUS) {
        this.DEAL_STATUS = DEAL_STATUS == null ? null : DEAL_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.BELONG_MERCHANT_ID：null
     */
    public BigDecimal getBELONG_MERCHANT_ID() {
        return BELONG_MERCHANT_ID;
    }

    /**
     * set method 
     *
     * @param BELONG_MERCHANT_ID  null
     */
    public void setBELONG_MERCHANT_ID(BigDecimal BELONG_MERCHANT_ID) {
        this.BELONG_MERCHANT_ID = BELONG_MERCHANT_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.BELONG_SHOP_ID：null
     */
    public BigDecimal getBELONG_SHOP_ID() {
        return BELONG_SHOP_ID;
    }

    /**
     * set method 
     *
     * @param BELONG_SHOP_ID  null
     */
    public void setBELONG_SHOP_ID(BigDecimal BELONG_SHOP_ID) {
        this.BELONG_SHOP_ID = BELONG_SHOP_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.BELONG_STAFF_ID：null
     */
    public BigDecimal getBELONG_STAFF_ID() {
        return BELONG_STAFF_ID;
    }

    /**
     * set method 
     *
     * @param BELONG_STAFF_ID  null
     */
    public void setBELONG_STAFF_ID(BigDecimal BELONG_STAFF_ID) {
        this.BELONG_STAFF_ID = BELONG_STAFF_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CREDENTIALS_PATH：null
     */
    public String getCREDENTIALS_PATH() {
        return CREDENTIALS_PATH;
    }

    /**
     * set method 
     *
     * @param CREDENTIALS_PATH  null
     */
    public void setCREDENTIALS_PATH(String CREDENTIALS_PATH) {
        this.CREDENTIALS_PATH = CREDENTIALS_PATH == null ? null : CREDENTIALS_PATH.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.DEAL_REASON：null
     */
    public String getDEAL_REASON() {
        return DEAL_REASON;
    }

    /**
     * set method 
     *
     * @param DEAL_REASON  null
     */
    public void setDEAL_REASON(String DEAL_REASON) {
        this.DEAL_REASON = DEAL_REASON == null ? null : DEAL_REASON.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.DEAL_PERSON_ID：null
     */
    public BigDecimal getDEAL_PERSON_ID() {
        return DEAL_PERSON_ID;
    }

    /**
     * set method 
     *
     * @param DEAL_PERSON_ID  null
     */
    public void setDEAL_PERSON_ID(BigDecimal DEAL_PERSON_ID) {
        this.DEAL_PERSON_ID = DEAL_PERSON_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.DEAL_TIME：null
     */
    public Date getDEAL_TIME() {
        return DEAL_TIME;
    }

    /**
     * set method 
     *
     * @param DEAL_TIME  null
     */
    public void setDEAL_TIME(Date DEAL_TIME) {
        this.DEAL_TIME = DEAL_TIME;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CREATED_TIME：null
     */
    public Date getCREATED_TIME() {
        return CREATED_TIME;
    }

    /**
     * set method 
     *
     * @param CREATED_TIME  null
     */
    public void setCREATED_TIME(Date CREATED_TIME) {
        this.CREATED_TIME = CREATED_TIME;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.CREATED_ID：null
     */
    public BigDecimal getCREATED_ID() {
        return CREATED_ID;
    }

    /**
     * set method 
     *
     * @param CREATED_ID  null
     */
    public void setCREATED_ID(BigDecimal CREATED_ID) {
        this.CREATED_ID = CREATED_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.UPDATED_TIME：null
     */
    public Date getUPDATED_TIME() {
        return UPDATED_TIME;
    }

    /**
     * set method 
     *
     * @param UPDATED_TIME  null
     */
    public void setUPDATED_TIME(Date UPDATED_TIME) {
        this.UPDATED_TIME = UPDATED_TIME;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_CHECK_EXCEPTION.UPDATED_ID：null
     */
    public BigDecimal getUPDATED_ID() {
        return UPDATED_ID;
    }

    /**
     * set method 
     *
     * @param UPDATED_ID  null
     */
    public void setUPDATED_ID(BigDecimal UPDATED_ID) {
        this.UPDATED_ID = UPDATED_ID;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T_check_exception other = (T_check_exception) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getORDER_NO() == null ? other.getORDER_NO() == null : this.getORDER_NO().equals(other.getORDER_NO()))
            && (this.getREFUND_NO() == null ? other.getREFUND_NO() == null : this.getREFUND_NO().equals(other.getREFUND_NO()))
            && (this.getBILL_ID() == null ? other.getBILL_ID() == null : this.getBILL_ID().equals(other.getBILL_ID()))
            && (this.getCHANNEL_ID() == null ? other.getCHANNEL_ID() == null : this.getCHANNEL_ID().equals(other.getCHANNEL_ID()))
            && (this.getBUSINESS_TYPE() == null ? other.getBUSINESS_TYPE() == null : this.getBUSINESS_TYPE().equals(other.getBUSINESS_TYPE()))
            && (this.getMERCHANT_ID() == null ? other.getMERCHANT_ID() == null : this.getMERCHANT_ID().equals(other.getMERCHANT_ID()))
            && (this.getSHOP_ID() == null ? other.getSHOP_ID() == null : this.getSHOP_ID().equals(other.getSHOP_ID()))
            && (this.getORG_ID() == null ? other.getORG_ID() == null : this.getORG_ID().equals(other.getORG_ID()))
            && (this.getTOP_ORG_ID() == null ? other.getTOP_ORG_ID() == null : this.getTOP_ORG_ID().equals(other.getTOP_ORG_ID()))
            && (this.getPAY_AMOUNT() == null ? other.getPAY_AMOUNT() == null : this.getPAY_AMOUNT().equals(other.getPAY_AMOUNT()))
            && (this.getORDER_TRADE_TIME() == null ? other.getORDER_TRADE_TIME() == null : this.getORDER_TRADE_TIME().equals(other.getORDER_TRADE_TIME()))
            && (this.getORDER_PAY_TYPE() == null ? other.getORDER_PAY_TYPE() == null : this.getORDER_PAY_TYPE().equals(other.getORDER_PAY_TYPE()))
            && (this.getORDER_STATUS() == null ? other.getORDER_STATUS() == null : this.getORDER_STATUS().equals(other.getORDER_STATUS()))
            && (this.getCHANNEL_ORDER_NO() == null ? other.getCHANNEL_ORDER_NO() == null : this.getCHANNEL_ORDER_NO().equals(other.getCHANNEL_ORDER_NO()))
            && (this.getCHANNEL_AMOUNT() == null ? other.getCHANNEL_AMOUNT() == null : this.getCHANNEL_AMOUNT().equals(other.getCHANNEL_AMOUNT()))
            && (this.getCHANNEL_DISCOUNT_AMOUNT() == null ? other.getCHANNEL_DISCOUNT_AMOUNT() == null : this.getCHANNEL_DISCOUNT_AMOUNT().equals(other.getCHANNEL_DISCOUNT_AMOUNT()))
            && (this.getCHANNEL_EXPIRE_TIME() == null ? other.getCHANNEL_EXPIRE_TIME() == null : this.getCHANNEL_EXPIRE_TIME().equals(other.getCHANNEL_EXPIRE_TIME()))
            && (this.getCHANNEL_PAY_TYPE() == null ? other.getCHANNEL_PAY_TYPE() == null : this.getCHANNEL_PAY_TYPE().equals(other.getCHANNEL_PAY_TYPE()))
            && (this.getCHECK_DATE() == null ? other.getCHECK_DATE() == null : this.getCHECK_DATE().equals(other.getCHECK_DATE()))
            && (this.getCHECK_STATUS() == null ? other.getCHECK_STATUS() == null : this.getCHECK_STATUS().equals(other.getCHECK_STATUS()))
            && (this.getDEAL_WAY() == null ? other.getDEAL_WAY() == null : this.getDEAL_WAY().equals(other.getDEAL_WAY()))
            && (this.getDEAL_STATUS() == null ? other.getDEAL_STATUS() == null : this.getDEAL_STATUS().equals(other.getDEAL_STATUS()))
            && (this.getBELONG_MERCHANT_ID() == null ? other.getBELONG_MERCHANT_ID() == null : this.getBELONG_MERCHANT_ID().equals(other.getBELONG_MERCHANT_ID()))
            && (this.getBELONG_SHOP_ID() == null ? other.getBELONG_SHOP_ID() == null : this.getBELONG_SHOP_ID().equals(other.getBELONG_SHOP_ID()))
            && (this.getBELONG_STAFF_ID() == null ? other.getBELONG_STAFF_ID() == null : this.getBELONG_STAFF_ID().equals(other.getBELONG_STAFF_ID()))
            && (this.getCREDENTIALS_PATH() == null ? other.getCREDENTIALS_PATH() == null : this.getCREDENTIALS_PATH().equals(other.getCREDENTIALS_PATH()))
            && (this.getDEAL_REASON() == null ? other.getDEAL_REASON() == null : this.getDEAL_REASON().equals(other.getDEAL_REASON()))
            && (this.getDEAL_PERSON_ID() == null ? other.getDEAL_PERSON_ID() == null : this.getDEAL_PERSON_ID().equals(other.getDEAL_PERSON_ID()))
            && (this.getDEAL_TIME() == null ? other.getDEAL_TIME() == null : this.getDEAL_TIME().equals(other.getDEAL_TIME()))
            && (this.getCREATED_TIME() == null ? other.getCREATED_TIME() == null : this.getCREATED_TIME().equals(other.getCREATED_TIME()))
            && (this.getCREATED_ID() == null ? other.getCREATED_ID() == null : this.getCREATED_ID().equals(other.getCREATED_ID()))
            && (this.getUPDATED_TIME() == null ? other.getUPDATED_TIME() == null : this.getUPDATED_TIME().equals(other.getUPDATED_TIME()))
            && (this.getUPDATED_ID() == null ? other.getUPDATED_ID() == null : this.getUPDATED_ID().equals(other.getUPDATED_ID()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getORDER_NO() == null) ? 0 : getORDER_NO().hashCode());
        result = prime * result + ((getREFUND_NO() == null) ? 0 : getREFUND_NO().hashCode());
        result = prime * result + ((getBILL_ID() == null) ? 0 : getBILL_ID().hashCode());
        result = prime * result + ((getCHANNEL_ID() == null) ? 0 : getCHANNEL_ID().hashCode());
        result = prime * result + ((getBUSINESS_TYPE() == null) ? 0 : getBUSINESS_TYPE().hashCode());
        result = prime * result + ((getMERCHANT_ID() == null) ? 0 : getMERCHANT_ID().hashCode());
        result = prime * result + ((getSHOP_ID() == null) ? 0 : getSHOP_ID().hashCode());
        result = prime * result + ((getORG_ID() == null) ? 0 : getORG_ID().hashCode());
        result = prime * result + ((getTOP_ORG_ID() == null) ? 0 : getTOP_ORG_ID().hashCode());
        result = prime * result + ((getPAY_AMOUNT() == null) ? 0 : getPAY_AMOUNT().hashCode());
        result = prime * result + ((getORDER_TRADE_TIME() == null) ? 0 : getORDER_TRADE_TIME().hashCode());
        result = prime * result + ((getORDER_PAY_TYPE() == null) ? 0 : getORDER_PAY_TYPE().hashCode());
        result = prime * result + ((getORDER_STATUS() == null) ? 0 : getORDER_STATUS().hashCode());
        result = prime * result + ((getCHANNEL_ORDER_NO() == null) ? 0 : getCHANNEL_ORDER_NO().hashCode());
        result = prime * result + ((getCHANNEL_AMOUNT() == null) ? 0 : getCHANNEL_AMOUNT().hashCode());
        result = prime * result + ((getCHANNEL_DISCOUNT_AMOUNT() == null) ? 0 : getCHANNEL_DISCOUNT_AMOUNT().hashCode());
        result = prime * result + ((getCHANNEL_EXPIRE_TIME() == null) ? 0 : getCHANNEL_EXPIRE_TIME().hashCode());
        result = prime * result + ((getCHANNEL_PAY_TYPE() == null) ? 0 : getCHANNEL_PAY_TYPE().hashCode());
        result = prime * result + ((getCHECK_DATE() == null) ? 0 : getCHECK_DATE().hashCode());
        result = prime * result + ((getCHECK_STATUS() == null) ? 0 : getCHECK_STATUS().hashCode());
        result = prime * result + ((getDEAL_WAY() == null) ? 0 : getDEAL_WAY().hashCode());
        result = prime * result + ((getDEAL_STATUS() == null) ? 0 : getDEAL_STATUS().hashCode());
        result = prime * result + ((getBELONG_MERCHANT_ID() == null) ? 0 : getBELONG_MERCHANT_ID().hashCode());
        result = prime * result + ((getBELONG_SHOP_ID() == null) ? 0 : getBELONG_SHOP_ID().hashCode());
        result = prime * result + ((getBELONG_STAFF_ID() == null) ? 0 : getBELONG_STAFF_ID().hashCode());
        result = prime * result + ((getCREDENTIALS_PATH() == null) ? 0 : getCREDENTIALS_PATH().hashCode());
        result = prime * result + ((getDEAL_REASON() == null) ? 0 : getDEAL_REASON().hashCode());
        result = prime * result + ((getDEAL_PERSON_ID() == null) ? 0 : getDEAL_PERSON_ID().hashCode());
        result = prime * result + ((getDEAL_TIME() == null) ? 0 : getDEAL_TIME().hashCode());
        result = prime * result + ((getCREATED_TIME() == null) ? 0 : getCREATED_TIME().hashCode());
        result = prime * result + ((getCREATED_ID() == null) ? 0 : getCREATED_ID().hashCode());
        result = prime * result + ((getUPDATED_TIME() == null) ? 0 : getUPDATED_TIME().hashCode());
        result = prime * result + ((getUPDATED_ID() == null) ? 0 : getUPDATED_ID().hashCode());
        return result;
    }
}