package org.ipay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class T_download_bill_file_log implements Serializable {
    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : ID
     */
    private BigDecimal ID;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : CHECK_DATE
     */
    private String CHECK_DATE;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : CHANNEL_ID
     */
    private BigDecimal CHANNEL_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : CHANNEL_CODE
     */
    private String CHANNEL_CODE;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : FILE_NAME
     */
    private String FILE_NAME;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : FILE_PATH
     */
    private String FILE_PATH;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : FILE_SIZE
     */
    private BigDecimal FILE_SIZE;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : START_DATE
     */
    private Date START_DATE;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : END_DATE
     */
    private Date END_DATE;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : STATUS
     */
    private String STATUS;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : CREATED_TIME
     */
    private Date CREATED_TIME;

    /**
     * 表 : IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     * 对应字段 : UPDATED_TIME
     */
    private Date UPDATED_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG
     *
     * @MBG Generated Mon Aug 07 19:43:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.ID：null
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.CHECK_DATE：null
     */
    public String getCHECK_DATE() {
        return CHECK_DATE;
    }

    /**
     * set method 
     *
     * @param CHECK_DATE  null
     */
    public void setCHECK_DATE(String CHECK_DATE) {
        this.CHECK_DATE = CHECK_DATE == null ? null : CHECK_DATE.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.CHANNEL_ID：null
     */
    public BigDecimal getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    /**
     * set method 
     *
     * @param CHANNEL_ID  null
     */
    public void setCHANNEL_ID(BigDecimal CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.CHANNEL_CODE：null
     */
    public String getCHANNEL_CODE() {
        return CHANNEL_CODE;
    }

    /**
     * set method 
     *
     * @param CHANNEL_CODE  null
     */
    public void setCHANNEL_CODE(String CHANNEL_CODE) {
        this.CHANNEL_CODE = CHANNEL_CODE == null ? null : CHANNEL_CODE.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.FILE_NAME：null
     */
    public String getFILE_NAME() {
        return FILE_NAME;
    }

    /**
     * set method 
     *
     * @param FILE_NAME  null
     */
    public void setFILE_NAME(String FILE_NAME) {
        this.FILE_NAME = FILE_NAME == null ? null : FILE_NAME.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.FILE_PATH：null
     */
    public String getFILE_PATH() {
        return FILE_PATH;
    }

    /**
     * set method 
     *
     * @param FILE_PATH  null
     */
    public void setFILE_PATH(String FILE_PATH) {
        this.FILE_PATH = FILE_PATH == null ? null : FILE_PATH.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.FILE_SIZE：null
     */
    public BigDecimal getFILE_SIZE() {
        return FILE_SIZE;
    }

    /**
     * set method 
     *
     * @param FILE_SIZE  null
     */
    public void setFILE_SIZE(BigDecimal FILE_SIZE) {
        this.FILE_SIZE = FILE_SIZE;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.START_DATE：null
     */
    public Date getSTART_DATE() {
        return START_DATE;
    }

    /**
     * set method 
     *
     * @param START_DATE  null
     */
    public void setSTART_DATE(Date START_DATE) {
        this.START_DATE = START_DATE;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.END_DATE：null
     */
    public Date getEND_DATE() {
        return END_DATE;
    }

    /**
     * set method 
     *
     * @param END_DATE  null
     */
    public void setEND_DATE(Date END_DATE) {
        this.END_DATE = END_DATE;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.STATUS：null
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * set method 
     *
     * @param STATUS  null
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.CREATED_TIME：null
     */
    public Date getCREATED_TIME() {
        return CREATED_TIME;
    }

    /**
     * set method 
     *
     * @param CREATED_TIME  null
     */
    public void setCREATED_TIME(Date CREATED_TIME) {
        this.CREATED_TIME = CREATED_TIME;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_DOWNLOAD_BILL_FILE_LOG.UPDATED_TIME：null
     */
    public Date getUPDATED_TIME() {
        return UPDATED_TIME;
    }

    /**
     * set method 
     *
     * @param UPDATED_TIME  null
     */
    public void setUPDATED_TIME(Date UPDATED_TIME) {
        this.UPDATED_TIME = UPDATED_TIME;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T_download_bill_file_log other = (T_download_bill_file_log) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getCHECK_DATE() == null ? other.getCHECK_DATE() == null : this.getCHECK_DATE().equals(other.getCHECK_DATE()))
            && (this.getCHANNEL_ID() == null ? other.getCHANNEL_ID() == null : this.getCHANNEL_ID().equals(other.getCHANNEL_ID()))
            && (this.getCHANNEL_CODE() == null ? other.getCHANNEL_CODE() == null : this.getCHANNEL_CODE().equals(other.getCHANNEL_CODE()))
            && (this.getFILE_NAME() == null ? other.getFILE_NAME() == null : this.getFILE_NAME().equals(other.getFILE_NAME()))
            && (this.getFILE_PATH() == null ? other.getFILE_PATH() == null : this.getFILE_PATH().equals(other.getFILE_PATH()))
            && (this.getFILE_SIZE() == null ? other.getFILE_SIZE() == null : this.getFILE_SIZE().equals(other.getFILE_SIZE()))
            && (this.getSTART_DATE() == null ? other.getSTART_DATE() == null : this.getSTART_DATE().equals(other.getSTART_DATE()))
            && (this.getEND_DATE() == null ? other.getEND_DATE() == null : this.getEND_DATE().equals(other.getEND_DATE()))
            && (this.getSTATUS() == null ? other.getSTATUS() == null : this.getSTATUS().equals(other.getSTATUS()))
            && (this.getCREATED_TIME() == null ? other.getCREATED_TIME() == null : this.getCREATED_TIME().equals(other.getCREATED_TIME()))
            && (this.getUPDATED_TIME() == null ? other.getUPDATED_TIME() == null : this.getUPDATED_TIME().equals(other.getUPDATED_TIME()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getCHECK_DATE() == null) ? 0 : getCHECK_DATE().hashCode());
        result = prime * result + ((getCHANNEL_ID() == null) ? 0 : getCHANNEL_ID().hashCode());
        result = prime * result + ((getCHANNEL_CODE() == null) ? 0 : getCHANNEL_CODE().hashCode());
        result = prime * result + ((getFILE_NAME() == null) ? 0 : getFILE_NAME().hashCode());
        result = prime * result + ((getFILE_PATH() == null) ? 0 : getFILE_PATH().hashCode());
        result = prime * result + ((getFILE_SIZE() == null) ? 0 : getFILE_SIZE().hashCode());
        result = prime * result + ((getSTART_DATE() == null) ? 0 : getSTART_DATE().hashCode());
        result = prime * result + ((getEND_DATE() == null) ? 0 : getEND_DATE().hashCode());
        result = prime * result + ((getSTATUS() == null) ? 0 : getSTATUS().hashCode());
        result = prime * result + ((getCREATED_TIME() == null) ? 0 : getCREATED_TIME().hashCode());
        result = prime * result + ((getUPDATED_TIME() == null) ? 0 : getUPDATED_TIME().hashCode());
        return result;
    }
}