package org.ipay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class T_ipay_organization implements Serializable {
    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ID
     */
    private Long ID;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ORG_NAME
     */
    private String ORG_NAME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ORG_CODE
     */
    private String ORG_CODE;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ORG_NO
     */
    private String ORG_NO;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : LINK_MAN
     */
    private String LINK_MAN;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : LINK_MAIL
     */
    private String LINK_MAIL;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : LINK_PHONE
     */
    private String LINK_PHONE;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ORG_TYPE
     */
    private String ORG_TYPE;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ADDRESS
     */
    private String ADDRESS;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ADDRESS_CODE
     */
    private String ADDRESS_CODE;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : PARENT_ID
     */
    private BigDecimal PARENT_ID;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : COMMISSION_ID
     */
    private BigDecimal COMMISSION_ID;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : BANK_ID
     */
    private BigDecimal BANK_ID;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ORG_DESC
     */
    private String ORG_DESC;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : VALIDATE_STATUS
     */
    private String VALIDATE_STATUS;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ACTIVATE_STATUS
     */
    private String ACTIVATE_STATUS;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : VALIDATE_USER_NAME
     */
    private String VALIDATE_USER_NAME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : VALIDATE_TIME
     */
    private Date VALIDATE_TIME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : VALIDATE_DESC
     */
    private String VALIDATE_DESC;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ACTIVATE_USER_NAME
     */
    private String ACTIVATE_USER_NAME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ACTIVATE_TIME
     */
    private Date ACTIVATE_TIME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : ACTIVATE_DESC
     */
    private String ACTIVATE_DESC;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : SORT
     */
    private BigDecimal SORT;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : STATUS
     */
    private Short STATUS;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : CREATED_TIME
     */
    private Date CREATED_TIME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : UPDATED_TIME
     */
    private Date UPDATED_TIME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : CREATED_NAME
     */
    private String CREATED_NAME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : UPDATED_NAME
     */
    private String UPDATED_NAME;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : UPDATED_ID
     */
    private String UPDATED_ID;

    /**
     * 表 : T_IPAY_ORGANIZATION
     * 对应字段 : TOP_ORG_ID
     */
    private BigDecimal TOP_ORG_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_IPAY_ORGANIZATION
     *
     * @MBG Generated Fri Sep 01 15:32:59 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ID：null
     */
    public Long getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ORG_NAME：null
     */
    public String getORG_NAME() {
        return ORG_NAME;
    }

    /**
     * set method 
     *
     * @param ORG_NAME  null
     */
    public void setORG_NAME(String ORG_NAME) {
        this.ORG_NAME = ORG_NAME == null ? null : ORG_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ORG_CODE：null
     */
    public String getORG_CODE() {
        return ORG_CODE;
    }

    /**
     * set method 
     *
     * @param ORG_CODE  null
     */
    public void setORG_CODE(String ORG_CODE) {
        this.ORG_CODE = ORG_CODE == null ? null : ORG_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ORG_NO：null
     */
    public String getORG_NO() {
        return ORG_NO;
    }

    /**
     * set method 
     *
     * @param ORG_NO  null
     */
    public void setORG_NO(String ORG_NO) {
        this.ORG_NO = ORG_NO == null ? null : ORG_NO.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.LINK_MAN：null
     */
    public String getLINK_MAN() {
        return LINK_MAN;
    }

    /**
     * set method 
     *
     * @param LINK_MAN  null
     */
    public void setLINK_MAN(String LINK_MAN) {
        this.LINK_MAN = LINK_MAN == null ? null : LINK_MAN.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.LINK_MAIL：null
     */
    public String getLINK_MAIL() {
        return LINK_MAIL;
    }

    /**
     * set method 
     *
     * @param LINK_MAIL  null
     */
    public void setLINK_MAIL(String LINK_MAIL) {
        this.LINK_MAIL = LINK_MAIL == null ? null : LINK_MAIL.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.LINK_PHONE：null
     */
    public String getLINK_PHONE() {
        return LINK_PHONE;
    }

    /**
     * set method 
     *
     * @param LINK_PHONE  null
     */
    public void setLINK_PHONE(String LINK_PHONE) {
        this.LINK_PHONE = LINK_PHONE == null ? null : LINK_PHONE.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ORG_TYPE：null
     */
    public String getORG_TYPE() {
        return ORG_TYPE;
    }

    /**
     * set method 
     *
     * @param ORG_TYPE  null
     */
    public void setORG_TYPE(String ORG_TYPE) {
        this.ORG_TYPE = ORG_TYPE == null ? null : ORG_TYPE.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ADDRESS：null
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * set method 
     *
     * @param ADDRESS  null
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ADDRESS_CODE：null
     */
    public String getADDRESS_CODE() {
        return ADDRESS_CODE;
    }

    /**
     * set method 
     *
     * @param ADDRESS_CODE  null
     */
    public void setADDRESS_CODE(String ADDRESS_CODE) {
        this.ADDRESS_CODE = ADDRESS_CODE == null ? null : ADDRESS_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.PARENT_ID：null
     */
    public BigDecimal getPARENT_ID() {
        return PARENT_ID;
    }

    /**
     * set method 
     *
     * @param PARENT_ID  null
     */
    public void setPARENT_ID(BigDecimal PARENT_ID) {
        this.PARENT_ID = PARENT_ID;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.COMMISSION_ID：null
     */
    public BigDecimal getCOMMISSION_ID() {
        return COMMISSION_ID;
    }

    /**
     * set method 
     *
     * @param COMMISSION_ID  null
     */
    public void setCOMMISSION_ID(BigDecimal COMMISSION_ID) {
        this.COMMISSION_ID = COMMISSION_ID;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.BANK_ID：null
     */
    public BigDecimal getBANK_ID() {
        return BANK_ID;
    }

    /**
     * set method 
     *
     * @param BANK_ID  null
     */
    public void setBANK_ID(BigDecimal BANK_ID) {
        this.BANK_ID = BANK_ID;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ORG_DESC：null
     */
    public String getORG_DESC() {
        return ORG_DESC;
    }

    /**
     * set method 
     *
     * @param ORG_DESC  null
     */
    public void setORG_DESC(String ORG_DESC) {
        this.ORG_DESC = ORG_DESC == null ? null : ORG_DESC.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.VALIDATE_STATUS：null
     */
    public String getVALIDATE_STATUS() {
        return VALIDATE_STATUS;
    }

    /**
     * set method 
     *
     * @param VALIDATE_STATUS  null
     */
    public void setVALIDATE_STATUS(String VALIDATE_STATUS) {
        this.VALIDATE_STATUS = VALIDATE_STATUS == null ? null : VALIDATE_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ACTIVATE_STATUS：null
     */
    public String getACTIVATE_STATUS() {
        return ACTIVATE_STATUS;
    }

    /**
     * set method 
     *
     * @param ACTIVATE_STATUS  null
     */
    public void setACTIVATE_STATUS(String ACTIVATE_STATUS) {
        this.ACTIVATE_STATUS = ACTIVATE_STATUS == null ? null : ACTIVATE_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.VALIDATE_USER_NAME：null
     */
    public String getVALIDATE_USER_NAME() {
        return VALIDATE_USER_NAME;
    }

    /**
     * set method 
     *
     * @param VALIDATE_USER_NAME  null
     */
    public void setVALIDATE_USER_NAME(String VALIDATE_USER_NAME) {
        this.VALIDATE_USER_NAME = VALIDATE_USER_NAME == null ? null : VALIDATE_USER_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.VALIDATE_TIME：null
     */
    public Date getVALIDATE_TIME() {
        return VALIDATE_TIME;
    }

    /**
     * set method 
     *
     * @param VALIDATE_TIME  null
     */
    public void setVALIDATE_TIME(Date VALIDATE_TIME) {
        this.VALIDATE_TIME = VALIDATE_TIME;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.VALIDATE_DESC：null
     */
    public String getVALIDATE_DESC() {
        return VALIDATE_DESC;
    }

    /**
     * set method 
     *
     * @param VALIDATE_DESC  null
     */
    public void setVALIDATE_DESC(String VALIDATE_DESC) {
        this.VALIDATE_DESC = VALIDATE_DESC == null ? null : VALIDATE_DESC.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ACTIVATE_USER_NAME：null
     */
    public String getACTIVATE_USER_NAME() {
        return ACTIVATE_USER_NAME;
    }

    /**
     * set method 
     *
     * @param ACTIVATE_USER_NAME  null
     */
    public void setACTIVATE_USER_NAME(String ACTIVATE_USER_NAME) {
        this.ACTIVATE_USER_NAME = ACTIVATE_USER_NAME == null ? null : ACTIVATE_USER_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ACTIVATE_TIME：null
     */
    public Date getACTIVATE_TIME() {
        return ACTIVATE_TIME;
    }

    /**
     * set method 
     *
     * @param ACTIVATE_TIME  null
     */
    public void setACTIVATE_TIME(Date ACTIVATE_TIME) {
        this.ACTIVATE_TIME = ACTIVATE_TIME;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.ACTIVATE_DESC：null
     */
    public String getACTIVATE_DESC() {
        return ACTIVATE_DESC;
    }

    /**
     * set method 
     *
     * @param ACTIVATE_DESC  null
     */
    public void setACTIVATE_DESC(String ACTIVATE_DESC) {
        this.ACTIVATE_DESC = ACTIVATE_DESC == null ? null : ACTIVATE_DESC.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.SORT：null
     */
    public BigDecimal getSORT() {
        return SORT;
    }

    /**
     * set method 
     *
     * @param SORT  null
     */
    public void setSORT(BigDecimal SORT) {
        this.SORT = SORT;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.STATUS：null
     */
    public Short getSTATUS() {
        return STATUS;
    }

    /**
     * set method 
     *
     * @param STATUS  null
     */
    public void setSTATUS(Short STATUS) {
        this.STATUS = STATUS;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.CREATED_TIME：null
     */
    public Date getCREATED_TIME() {
        return CREATED_TIME;
    }

    /**
     * set method 
     *
     * @param CREATED_TIME  null
     */
    public void setCREATED_TIME(Date CREATED_TIME) {
        this.CREATED_TIME = CREATED_TIME;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.UPDATED_TIME：null
     */
    public Date getUPDATED_TIME() {
        return UPDATED_TIME;
    }

    /**
     * set method 
     *
     * @param UPDATED_TIME  null
     */
    public void setUPDATED_TIME(Date UPDATED_TIME) {
        this.UPDATED_TIME = UPDATED_TIME;
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.CREATED_NAME：null
     */
    public String getCREATED_NAME() {
        return CREATED_NAME;
    }

    /**
     * set method 
     *
     * @param CREATED_NAME  null
     */
    public void setCREATED_NAME(String CREATED_NAME) {
        this.CREATED_NAME = CREATED_NAME == null ? null : CREATED_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.UPDATED_NAME：null
     */
    public String getUPDATED_NAME() {
        return UPDATED_NAME;
    }

    /**
     * set method 
     *
     * @param UPDATED_NAME  null
     */
    public void setUPDATED_NAME(String UPDATED_NAME) {
        this.UPDATED_NAME = UPDATED_NAME == null ? null : UPDATED_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.UPDATED_ID：null
     */
    public String getUPDATED_ID() {
        return UPDATED_ID;
    }

    /**
     * set method 
     *
     * @param UPDATED_ID  null
     */
    public void setUPDATED_ID(String UPDATED_ID) {
        this.UPDATED_ID = UPDATED_ID == null ? null : UPDATED_ID.trim();
    }

    /**
     * get method 
     *
     * @return T_IPAY_ORGANIZATION.TOP_ORG_ID：null
     */
    public BigDecimal getTOP_ORG_ID() {
        return TOP_ORG_ID;
    }

    /**
     * set method 
     *
     * @param TOP_ORG_ID  null
     */
    public void setTOP_ORG_ID(BigDecimal TOP_ORG_ID) {
        this.TOP_ORG_ID = TOP_ORG_ID;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T_ipay_organization other = (T_ipay_organization) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getORG_NAME() == null ? other.getORG_NAME() == null : this.getORG_NAME().equals(other.getORG_NAME()))
            && (this.getORG_CODE() == null ? other.getORG_CODE() == null : this.getORG_CODE().equals(other.getORG_CODE()))
            && (this.getORG_NO() == null ? other.getORG_NO() == null : this.getORG_NO().equals(other.getORG_NO()))
            && (this.getLINK_MAN() == null ? other.getLINK_MAN() == null : this.getLINK_MAN().equals(other.getLINK_MAN()))
            && (this.getLINK_MAIL() == null ? other.getLINK_MAIL() == null : this.getLINK_MAIL().equals(other.getLINK_MAIL()))
            && (this.getLINK_PHONE() == null ? other.getLINK_PHONE() == null : this.getLINK_PHONE().equals(other.getLINK_PHONE()))
            && (this.getORG_TYPE() == null ? other.getORG_TYPE() == null : this.getORG_TYPE().equals(other.getORG_TYPE()))
            && (this.getADDRESS() == null ? other.getADDRESS() == null : this.getADDRESS().equals(other.getADDRESS()))
            && (this.getADDRESS_CODE() == null ? other.getADDRESS_CODE() == null : this.getADDRESS_CODE().equals(other.getADDRESS_CODE()))
            && (this.getPARENT_ID() == null ? other.getPARENT_ID() == null : this.getPARENT_ID().equals(other.getPARENT_ID()))
            && (this.getCOMMISSION_ID() == null ? other.getCOMMISSION_ID() == null : this.getCOMMISSION_ID().equals(other.getCOMMISSION_ID()))
            && (this.getBANK_ID() == null ? other.getBANK_ID() == null : this.getBANK_ID().equals(other.getBANK_ID()))
            && (this.getORG_DESC() == null ? other.getORG_DESC() == null : this.getORG_DESC().equals(other.getORG_DESC()))
            && (this.getVALIDATE_STATUS() == null ? other.getVALIDATE_STATUS() == null : this.getVALIDATE_STATUS().equals(other.getVALIDATE_STATUS()))
            && (this.getACTIVATE_STATUS() == null ? other.getACTIVATE_STATUS() == null : this.getACTIVATE_STATUS().equals(other.getACTIVATE_STATUS()))
            && (this.getVALIDATE_USER_NAME() == null ? other.getVALIDATE_USER_NAME() == null : this.getVALIDATE_USER_NAME().equals(other.getVALIDATE_USER_NAME()))
            && (this.getVALIDATE_TIME() == null ? other.getVALIDATE_TIME() == null : this.getVALIDATE_TIME().equals(other.getVALIDATE_TIME()))
            && (this.getVALIDATE_DESC() == null ? other.getVALIDATE_DESC() == null : this.getVALIDATE_DESC().equals(other.getVALIDATE_DESC()))
            && (this.getACTIVATE_USER_NAME() == null ? other.getACTIVATE_USER_NAME() == null : this.getACTIVATE_USER_NAME().equals(other.getACTIVATE_USER_NAME()))
            && (this.getACTIVATE_TIME() == null ? other.getACTIVATE_TIME() == null : this.getACTIVATE_TIME().equals(other.getACTIVATE_TIME()))
            && (this.getACTIVATE_DESC() == null ? other.getACTIVATE_DESC() == null : this.getACTIVATE_DESC().equals(other.getACTIVATE_DESC()))
            && (this.getSORT() == null ? other.getSORT() == null : this.getSORT().equals(other.getSORT()))
            && (this.getSTATUS() == null ? other.getSTATUS() == null : this.getSTATUS().equals(other.getSTATUS()))
            && (this.getCREATED_TIME() == null ? other.getCREATED_TIME() == null : this.getCREATED_TIME().equals(other.getCREATED_TIME()))
            && (this.getUPDATED_TIME() == null ? other.getUPDATED_TIME() == null : this.getUPDATED_TIME().equals(other.getUPDATED_TIME()))
            && (this.getCREATED_NAME() == null ? other.getCREATED_NAME() == null : this.getCREATED_NAME().equals(other.getCREATED_NAME()))
            && (this.getUPDATED_NAME() == null ? other.getUPDATED_NAME() == null : this.getUPDATED_NAME().equals(other.getUPDATED_NAME()))
            && (this.getUPDATED_ID() == null ? other.getUPDATED_ID() == null : this.getUPDATED_ID().equals(other.getUPDATED_ID()))
            && (this.getTOP_ORG_ID() == null ? other.getTOP_ORG_ID() == null : this.getTOP_ORG_ID().equals(other.getTOP_ORG_ID()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getORG_NAME() == null) ? 0 : getORG_NAME().hashCode());
        result = prime * result + ((getORG_CODE() == null) ? 0 : getORG_CODE().hashCode());
        result = prime * result + ((getORG_NO() == null) ? 0 : getORG_NO().hashCode());
        result = prime * result + ((getLINK_MAN() == null) ? 0 : getLINK_MAN().hashCode());
        result = prime * result + ((getLINK_MAIL() == null) ? 0 : getLINK_MAIL().hashCode());
        result = prime * result + ((getLINK_PHONE() == null) ? 0 : getLINK_PHONE().hashCode());
        result = prime * result + ((getORG_TYPE() == null) ? 0 : getORG_TYPE().hashCode());
        result = prime * result + ((getADDRESS() == null) ? 0 : getADDRESS().hashCode());
        result = prime * result + ((getADDRESS_CODE() == null) ? 0 : getADDRESS_CODE().hashCode());
        result = prime * result + ((getPARENT_ID() == null) ? 0 : getPARENT_ID().hashCode());
        result = prime * result + ((getCOMMISSION_ID() == null) ? 0 : getCOMMISSION_ID().hashCode());
        result = prime * result + ((getBANK_ID() == null) ? 0 : getBANK_ID().hashCode());
        result = prime * result + ((getORG_DESC() == null) ? 0 : getORG_DESC().hashCode());
        result = prime * result + ((getVALIDATE_STATUS() == null) ? 0 : getVALIDATE_STATUS().hashCode());
        result = prime * result + ((getACTIVATE_STATUS() == null) ? 0 : getACTIVATE_STATUS().hashCode());
        result = prime * result + ((getVALIDATE_USER_NAME() == null) ? 0 : getVALIDATE_USER_NAME().hashCode());
        result = prime * result + ((getVALIDATE_TIME() == null) ? 0 : getVALIDATE_TIME().hashCode());
        result = prime * result + ((getVALIDATE_DESC() == null) ? 0 : getVALIDATE_DESC().hashCode());
        result = prime * result + ((getACTIVATE_USER_NAME() == null) ? 0 : getACTIVATE_USER_NAME().hashCode());
        result = prime * result + ((getACTIVATE_TIME() == null) ? 0 : getACTIVATE_TIME().hashCode());
        result = prime * result + ((getACTIVATE_DESC() == null) ? 0 : getACTIVATE_DESC().hashCode());
        result = prime * result + ((getSORT() == null) ? 0 : getSORT().hashCode());
        result = prime * result + ((getSTATUS() == null) ? 0 : getSTATUS().hashCode());
        result = prime * result + ((getCREATED_TIME() == null) ? 0 : getCREATED_TIME().hashCode());
        result = prime * result + ((getUPDATED_TIME() == null) ? 0 : getUPDATED_TIME().hashCode());
        result = prime * result + ((getCREATED_NAME() == null) ? 0 : getCREATED_NAME().hashCode());
        result = prime * result + ((getUPDATED_NAME() == null) ? 0 : getUPDATED_NAME().hashCode());
        result = prime * result + ((getUPDATED_ID() == null) ? 0 : getUPDATED_ID().hashCode());
        result = prime * result + ((getTOP_ORG_ID() == null) ? 0 : getTOP_ORG_ID().hashCode());
        return result;
    }
}