package org.ipay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class T_merchant_shop implements Serializable {
    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : ID
     */
    private Long ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : ORG_ID
     */
    private BigDecimal ORG_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : PARENT_ID
     */
    private BigDecimal PARENT_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : TREE_PATH
     */
    private String TREE_PATH;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : MERCHANT_ID
     */
    private BigDecimal MERCHANT_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : SHOP_CODE
     */
    private String SHOP_CODE;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : SHOP_NAME
     */
    private String SHOP_NAME;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : SHOP_SHORT_NAME
     */
    private String SHOP_SHORT_NAME;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : TYPE
     */
    private String TYPE;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : COMMISSION_RATE
     */
    private BigDecimal COMMISSION_RATE;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : INDEPENDENT_ACCOUNTING
     */
    private String INDEPENDENT_ACCOUNTING;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : REGISTERED_BANK
     */
    private String REGISTERED_BANK;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : ACCOUNT_TYPE
     */
    private String ACCOUNT_TYPE;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : ACCOUNTING_ACCOUNT_NAME
     */
    private String ACCOUNTING_ACCOUNT_NAME;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : ACCOUNTING_ACCOUNT_NO
     */
    private String ACCOUNTING_ACCOUNT_NO;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : ONLINE_STATUS
     */
    private String ONLINE_STATUS;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : APPROVER
     */
    private String APPROVER;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : APPROVAL_REMARK
     */
    private String APPROVAL_REMARK;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : APPROVAL_STATUS
     */
    private String APPROVAL_STATUS;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : APPROVAL_TIME
     */
    private Date APPROVAL_TIME;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : PROVINCE_ID
     */
    private BigDecimal PROVINCE_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : CITY_ID
     */
    private BigDecimal CITY_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : DISTRICT_ID
     */
    private BigDecimal DISTRICT_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : ADDRESS
     */
    private String ADDRESS;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : CONCERN_TYPE
     */
    private String CONCERN_TYPE;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : BUSINESS_DISTRICT_ID
     */
    private BigDecimal BUSINESS_DISTRICT_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : INDUSTRY_ID
     */
    private BigDecimal INDUSTRY_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : CONTACT_PERSON
     */
    private String CONTACT_PERSON;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : CONTACT_PHONE
     */
    private String CONTACT_PHONE;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : SHOP_INTRODUCTION
     */
    private String SHOP_INTRODUCTION;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : REMARK
     */
    private String REMARK;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : URL_SHOP_PIC1
     */
    private String URL_SHOP_PIC1;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : URL_SHOP_PIC2
     */
    private String URL_SHOP_PIC2;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : STATUS
     */
    private String STATUS;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : MODIFY_ID
     */
    private BigDecimal MODIFY_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : MODIFY_TIME
     */
    private Date MODIFY_TIME;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : CREATED_ID
     */
    private BigDecimal CREATED_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : CREATED_TIME
     */
    private Date CREATED_TIME;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : UPDATED_ID
     */
    private BigDecimal UPDATED_ID;

    /**
     * 表 : T_MERCHANT_SHOP
     * 对应字段 : UPDATED_TIME
     */
    private Date UPDATED_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MERCHANT_SHOP
     *
     * @MBG Generated Tue Sep 12 15:50:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.ID：null
     */
    public Long getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.ORG_ID：null
     */
    public BigDecimal getORG_ID() {
        return ORG_ID;
    }

    /**
     * set method 
     *
     * @param ORG_ID  null
     */
    public void setORG_ID(BigDecimal ORG_ID) {
        this.ORG_ID = ORG_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.PARENT_ID：null
     */
    public BigDecimal getPARENT_ID() {
        return PARENT_ID;
    }

    /**
     * set method 
     *
     * @param PARENT_ID  null
     */
    public void setPARENT_ID(BigDecimal PARENT_ID) {
        this.PARENT_ID = PARENT_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.TREE_PATH：null
     */
    public String getTREE_PATH() {
        return TREE_PATH;
    }

    /**
     * set method 
     *
     * @param TREE_PATH  null
     */
    public void setTREE_PATH(String TREE_PATH) {
        this.TREE_PATH = TREE_PATH == null ? null : TREE_PATH.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.MERCHANT_ID：null
     */
    public BigDecimal getMERCHANT_ID() {
        return MERCHANT_ID;
    }

    /**
     * set method 
     *
     * @param MERCHANT_ID  null
     */
    public void setMERCHANT_ID(BigDecimal MERCHANT_ID) {
        this.MERCHANT_ID = MERCHANT_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.SHOP_CODE：null
     */
    public String getSHOP_CODE() {
        return SHOP_CODE;
    }

    /**
     * set method 
     *
     * @param SHOP_CODE  null
     */
    public void setSHOP_CODE(String SHOP_CODE) {
        this.SHOP_CODE = SHOP_CODE == null ? null : SHOP_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.SHOP_NAME：null
     */
    public String getSHOP_NAME() {
        return SHOP_NAME;
    }

    /**
     * set method 
     *
     * @param SHOP_NAME  null
     */
    public void setSHOP_NAME(String SHOP_NAME) {
        this.SHOP_NAME = SHOP_NAME == null ? null : SHOP_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.SHOP_SHORT_NAME：null
     */
    public String getSHOP_SHORT_NAME() {
        return SHOP_SHORT_NAME;
    }

    /**
     * set method 
     *
     * @param SHOP_SHORT_NAME  null
     */
    public void setSHOP_SHORT_NAME(String SHOP_SHORT_NAME) {
        this.SHOP_SHORT_NAME = SHOP_SHORT_NAME == null ? null : SHOP_SHORT_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.TYPE：null
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * set method 
     *
     * @param TYPE  null
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.COMMISSION_RATE：null
     */
    public BigDecimal getCOMMISSION_RATE() {
        return COMMISSION_RATE;
    }

    /**
     * set method 
     *
     * @param COMMISSION_RATE  null
     */
    public void setCOMMISSION_RATE(BigDecimal COMMISSION_RATE) {
        this.COMMISSION_RATE = COMMISSION_RATE;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.INDEPENDENT_ACCOUNTING：null
     */
    public String getINDEPENDENT_ACCOUNTING() {
        return INDEPENDENT_ACCOUNTING;
    }

    /**
     * set method 
     *
     * @param INDEPENDENT_ACCOUNTING  null
     */
    public void setINDEPENDENT_ACCOUNTING(String INDEPENDENT_ACCOUNTING) {
        this.INDEPENDENT_ACCOUNTING = INDEPENDENT_ACCOUNTING == null ? null : INDEPENDENT_ACCOUNTING.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.REGISTERED_BANK：null
     */
    public String getREGISTERED_BANK() {
        return REGISTERED_BANK;
    }

    /**
     * set method 
     *
     * @param REGISTERED_BANK  null
     */
    public void setREGISTERED_BANK(String REGISTERED_BANK) {
        this.REGISTERED_BANK = REGISTERED_BANK == null ? null : REGISTERED_BANK.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.ACCOUNT_TYPE：null
     */
    public String getACCOUNT_TYPE() {
        return ACCOUNT_TYPE;
    }

    /**
     * set method 
     *
     * @param ACCOUNT_TYPE  null
     */
    public void setACCOUNT_TYPE(String ACCOUNT_TYPE) {
        this.ACCOUNT_TYPE = ACCOUNT_TYPE == null ? null : ACCOUNT_TYPE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.ACCOUNTING_ACCOUNT_NAME：null
     */
    public String getACCOUNTING_ACCOUNT_NAME() {
        return ACCOUNTING_ACCOUNT_NAME;
    }

    /**
     * set method 
     *
     * @param ACCOUNTING_ACCOUNT_NAME  null
     */
    public void setACCOUNTING_ACCOUNT_NAME(String ACCOUNTING_ACCOUNT_NAME) {
        this.ACCOUNTING_ACCOUNT_NAME = ACCOUNTING_ACCOUNT_NAME == null ? null : ACCOUNTING_ACCOUNT_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.ACCOUNTING_ACCOUNT_NO：null
     */
    public String getACCOUNTING_ACCOUNT_NO() {
        return ACCOUNTING_ACCOUNT_NO;
    }

    /**
     * set method 
     *
     * @param ACCOUNTING_ACCOUNT_NO  null
     */
    public void setACCOUNTING_ACCOUNT_NO(String ACCOUNTING_ACCOUNT_NO) {
        this.ACCOUNTING_ACCOUNT_NO = ACCOUNTING_ACCOUNT_NO == null ? null : ACCOUNTING_ACCOUNT_NO.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.ONLINE_STATUS：null
     */
    public String getONLINE_STATUS() {
        return ONLINE_STATUS;
    }

    /**
     * set method 
     *
     * @param ONLINE_STATUS  null
     */
    public void setONLINE_STATUS(String ONLINE_STATUS) {
        this.ONLINE_STATUS = ONLINE_STATUS == null ? null : ONLINE_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.APPROVER：null
     */
    public String getAPPROVER() {
        return APPROVER;
    }

    /**
     * set method 
     *
     * @param APPROVER  null
     */
    public void setAPPROVER(String APPROVER) {
        this.APPROVER = APPROVER == null ? null : APPROVER.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.APPROVAL_REMARK：null
     */
    public String getAPPROVAL_REMARK() {
        return APPROVAL_REMARK;
    }

    /**
     * set method 
     *
     * @param APPROVAL_REMARK  null
     */
    public void setAPPROVAL_REMARK(String APPROVAL_REMARK) {
        this.APPROVAL_REMARK = APPROVAL_REMARK == null ? null : APPROVAL_REMARK.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.APPROVAL_STATUS：null
     */
    public String getAPPROVAL_STATUS() {
        return APPROVAL_STATUS;
    }

    /**
     * set method 
     *
     * @param APPROVAL_STATUS  null
     */
    public void setAPPROVAL_STATUS(String APPROVAL_STATUS) {
        this.APPROVAL_STATUS = APPROVAL_STATUS == null ? null : APPROVAL_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.APPROVAL_TIME：null
     */
    public Date getAPPROVAL_TIME() {
        return APPROVAL_TIME;
    }

    /**
     * set method 
     *
     * @param APPROVAL_TIME  null
     */
    public void setAPPROVAL_TIME(Date APPROVAL_TIME) {
        this.APPROVAL_TIME = APPROVAL_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.PROVINCE_ID：null
     */
    public BigDecimal getPROVINCE_ID() {
        return PROVINCE_ID;
    }

    /**
     * set method 
     *
     * @param PROVINCE_ID  null
     */
    public void setPROVINCE_ID(BigDecimal PROVINCE_ID) {
        this.PROVINCE_ID = PROVINCE_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.CITY_ID：null
     */
    public BigDecimal getCITY_ID() {
        return CITY_ID;
    }

    /**
     * set method 
     *
     * @param CITY_ID  null
     */
    public void setCITY_ID(BigDecimal CITY_ID) {
        this.CITY_ID = CITY_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.DISTRICT_ID：null
     */
    public BigDecimal getDISTRICT_ID() {
        return DISTRICT_ID;
    }

    /**
     * set method 
     *
     * @param DISTRICT_ID  null
     */
    public void setDISTRICT_ID(BigDecimal DISTRICT_ID) {
        this.DISTRICT_ID = DISTRICT_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.ADDRESS：null
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * set method 
     *
     * @param ADDRESS  null
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.CONCERN_TYPE：null
     */
    public String getCONCERN_TYPE() {
        return CONCERN_TYPE;
    }

    /**
     * set method 
     *
     * @param CONCERN_TYPE  null
     */
    public void setCONCERN_TYPE(String CONCERN_TYPE) {
        this.CONCERN_TYPE = CONCERN_TYPE == null ? null : CONCERN_TYPE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.BUSINESS_DISTRICT_ID：null
     */
    public BigDecimal getBUSINESS_DISTRICT_ID() {
        return BUSINESS_DISTRICT_ID;
    }

    /**
     * set method 
     *
     * @param BUSINESS_DISTRICT_ID  null
     */
    public void setBUSINESS_DISTRICT_ID(BigDecimal BUSINESS_DISTRICT_ID) {
        this.BUSINESS_DISTRICT_ID = BUSINESS_DISTRICT_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.INDUSTRY_ID：null
     */
    public BigDecimal getINDUSTRY_ID() {
        return INDUSTRY_ID;
    }

    /**
     * set method 
     *
     * @param INDUSTRY_ID  null
     */
    public void setINDUSTRY_ID(BigDecimal INDUSTRY_ID) {
        this.INDUSTRY_ID = INDUSTRY_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.CONTACT_PERSON：null
     */
    public String getCONTACT_PERSON() {
        return CONTACT_PERSON;
    }

    /**
     * set method 
     *
     * @param CONTACT_PERSON  null
     */
    public void setCONTACT_PERSON(String CONTACT_PERSON) {
        this.CONTACT_PERSON = CONTACT_PERSON == null ? null : CONTACT_PERSON.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.CONTACT_PHONE：null
     */
    public String getCONTACT_PHONE() {
        return CONTACT_PHONE;
    }

    /**
     * set method 
     *
     * @param CONTACT_PHONE  null
     */
    public void setCONTACT_PHONE(String CONTACT_PHONE) {
        this.CONTACT_PHONE = CONTACT_PHONE == null ? null : CONTACT_PHONE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.SHOP_INTRODUCTION：null
     */
    public String getSHOP_INTRODUCTION() {
        return SHOP_INTRODUCTION;
    }

    /**
     * set method 
     *
     * @param SHOP_INTRODUCTION  null
     */
    public void setSHOP_INTRODUCTION(String SHOP_INTRODUCTION) {
        this.SHOP_INTRODUCTION = SHOP_INTRODUCTION == null ? null : SHOP_INTRODUCTION.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.REMARK：null
     */
    public String getREMARK() {
        return REMARK;
    }

    /**
     * set method 
     *
     * @param REMARK  null
     */
    public void setREMARK(String REMARK) {
        this.REMARK = REMARK == null ? null : REMARK.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.URL_SHOP_PIC1：null
     */
    public String getURL_SHOP_PIC1() {
        return URL_SHOP_PIC1;
    }

    /**
     * set method 
     *
     * @param URL_SHOP_PIC1  null
     */
    public void setURL_SHOP_PIC1(String URL_SHOP_PIC1) {
        this.URL_SHOP_PIC1 = URL_SHOP_PIC1 == null ? null : URL_SHOP_PIC1.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.URL_SHOP_PIC2：null
     */
    public String getURL_SHOP_PIC2() {
        return URL_SHOP_PIC2;
    }

    /**
     * set method 
     *
     * @param URL_SHOP_PIC2  null
     */
    public void setURL_SHOP_PIC2(String URL_SHOP_PIC2) {
        this.URL_SHOP_PIC2 = URL_SHOP_PIC2 == null ? null : URL_SHOP_PIC2.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.STATUS：null
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * set method 
     *
     * @param STATUS  null
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.MODIFY_ID：null
     */
    public BigDecimal getMODIFY_ID() {
        return MODIFY_ID;
    }

    /**
     * set method 
     *
     * @param MODIFY_ID  null
     */
    public void setMODIFY_ID(BigDecimal MODIFY_ID) {
        this.MODIFY_ID = MODIFY_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.MODIFY_TIME：null
     */
    public Date getMODIFY_TIME() {
        return MODIFY_TIME;
    }

    /**
     * set method 
     *
     * @param MODIFY_TIME  null
     */
    public void setMODIFY_TIME(Date MODIFY_TIME) {
        this.MODIFY_TIME = MODIFY_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.CREATED_ID：null
     */
    public BigDecimal getCREATED_ID() {
        return CREATED_ID;
    }

    /**
     * set method 
     *
     * @param CREATED_ID  null
     */
    public void setCREATED_ID(BigDecimal CREATED_ID) {
        this.CREATED_ID = CREATED_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.CREATED_TIME：null
     */
    public Date getCREATED_TIME() {
        return CREATED_TIME;
    }

    /**
     * set method 
     *
     * @param CREATED_TIME  null
     */
    public void setCREATED_TIME(Date CREATED_TIME) {
        this.CREATED_TIME = CREATED_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.UPDATED_ID：null
     */
    public BigDecimal getUPDATED_ID() {
        return UPDATED_ID;
    }

    /**
     * set method 
     *
     * @param UPDATED_ID  null
     */
    public void setUPDATED_ID(BigDecimal UPDATED_ID) {
        this.UPDATED_ID = UPDATED_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT_SHOP.UPDATED_TIME：null
     */
    public Date getUPDATED_TIME() {
        return UPDATED_TIME;
    }

    /**
     * set method 
     *
     * @param UPDATED_TIME  null
     */
    public void setUPDATED_TIME(Date UPDATED_TIME) {
        this.UPDATED_TIME = UPDATED_TIME;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T_merchant_shop other = (T_merchant_shop) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getORG_ID() == null ? other.getORG_ID() == null : this.getORG_ID().equals(other.getORG_ID()))
            && (this.getPARENT_ID() == null ? other.getPARENT_ID() == null : this.getPARENT_ID().equals(other.getPARENT_ID()))
            && (this.getTREE_PATH() == null ? other.getTREE_PATH() == null : this.getTREE_PATH().equals(other.getTREE_PATH()))
            && (this.getMERCHANT_ID() == null ? other.getMERCHANT_ID() == null : this.getMERCHANT_ID().equals(other.getMERCHANT_ID()))
            && (this.getSHOP_CODE() == null ? other.getSHOP_CODE() == null : this.getSHOP_CODE().equals(other.getSHOP_CODE()))
            && (this.getSHOP_NAME() == null ? other.getSHOP_NAME() == null : this.getSHOP_NAME().equals(other.getSHOP_NAME()))
            && (this.getSHOP_SHORT_NAME() == null ? other.getSHOP_SHORT_NAME() == null : this.getSHOP_SHORT_NAME().equals(other.getSHOP_SHORT_NAME()))
            && (this.getTYPE() == null ? other.getTYPE() == null : this.getTYPE().equals(other.getTYPE()))
            && (this.getCOMMISSION_RATE() == null ? other.getCOMMISSION_RATE() == null : this.getCOMMISSION_RATE().equals(other.getCOMMISSION_RATE()))
            && (this.getINDEPENDENT_ACCOUNTING() == null ? other.getINDEPENDENT_ACCOUNTING() == null : this.getINDEPENDENT_ACCOUNTING().equals(other.getINDEPENDENT_ACCOUNTING()))
            && (this.getREGISTERED_BANK() == null ? other.getREGISTERED_BANK() == null : this.getREGISTERED_BANK().equals(other.getREGISTERED_BANK()))
            && (this.getACCOUNT_TYPE() == null ? other.getACCOUNT_TYPE() == null : this.getACCOUNT_TYPE().equals(other.getACCOUNT_TYPE()))
            && (this.getACCOUNTING_ACCOUNT_NAME() == null ? other.getACCOUNTING_ACCOUNT_NAME() == null : this.getACCOUNTING_ACCOUNT_NAME().equals(other.getACCOUNTING_ACCOUNT_NAME()))
            && (this.getACCOUNTING_ACCOUNT_NO() == null ? other.getACCOUNTING_ACCOUNT_NO() == null : this.getACCOUNTING_ACCOUNT_NO().equals(other.getACCOUNTING_ACCOUNT_NO()))
            && (this.getONLINE_STATUS() == null ? other.getONLINE_STATUS() == null : this.getONLINE_STATUS().equals(other.getONLINE_STATUS()))
            && (this.getAPPROVER() == null ? other.getAPPROVER() == null : this.getAPPROVER().equals(other.getAPPROVER()))
            && (this.getAPPROVAL_REMARK() == null ? other.getAPPROVAL_REMARK() == null : this.getAPPROVAL_REMARK().equals(other.getAPPROVAL_REMARK()))
            && (this.getAPPROVAL_STATUS() == null ? other.getAPPROVAL_STATUS() == null : this.getAPPROVAL_STATUS().equals(other.getAPPROVAL_STATUS()))
            && (this.getAPPROVAL_TIME() == null ? other.getAPPROVAL_TIME() == null : this.getAPPROVAL_TIME().equals(other.getAPPROVAL_TIME()))
            && (this.getPROVINCE_ID() == null ? other.getPROVINCE_ID() == null : this.getPROVINCE_ID().equals(other.getPROVINCE_ID()))
            && (this.getCITY_ID() == null ? other.getCITY_ID() == null : this.getCITY_ID().equals(other.getCITY_ID()))
            && (this.getDISTRICT_ID() == null ? other.getDISTRICT_ID() == null : this.getDISTRICT_ID().equals(other.getDISTRICT_ID()))
            && (this.getADDRESS() == null ? other.getADDRESS() == null : this.getADDRESS().equals(other.getADDRESS()))
            && (this.getCONCERN_TYPE() == null ? other.getCONCERN_TYPE() == null : this.getCONCERN_TYPE().equals(other.getCONCERN_TYPE()))
            && (this.getBUSINESS_DISTRICT_ID() == null ? other.getBUSINESS_DISTRICT_ID() == null : this.getBUSINESS_DISTRICT_ID().equals(other.getBUSINESS_DISTRICT_ID()))
            && (this.getINDUSTRY_ID() == null ? other.getINDUSTRY_ID() == null : this.getINDUSTRY_ID().equals(other.getINDUSTRY_ID()))
            && (this.getCONTACT_PERSON() == null ? other.getCONTACT_PERSON() == null : this.getCONTACT_PERSON().equals(other.getCONTACT_PERSON()))
            && (this.getCONTACT_PHONE() == null ? other.getCONTACT_PHONE() == null : this.getCONTACT_PHONE().equals(other.getCONTACT_PHONE()))
            && (this.getSHOP_INTRODUCTION() == null ? other.getSHOP_INTRODUCTION() == null : this.getSHOP_INTRODUCTION().equals(other.getSHOP_INTRODUCTION()))
            && (this.getREMARK() == null ? other.getREMARK() == null : this.getREMARK().equals(other.getREMARK()))
            && (this.getURL_SHOP_PIC1() == null ? other.getURL_SHOP_PIC1() == null : this.getURL_SHOP_PIC1().equals(other.getURL_SHOP_PIC1()))
            && (this.getURL_SHOP_PIC2() == null ? other.getURL_SHOP_PIC2() == null : this.getURL_SHOP_PIC2().equals(other.getURL_SHOP_PIC2()))
            && (this.getSTATUS() == null ? other.getSTATUS() == null : this.getSTATUS().equals(other.getSTATUS()))
            && (this.getMODIFY_ID() == null ? other.getMODIFY_ID() == null : this.getMODIFY_ID().equals(other.getMODIFY_ID()))
            && (this.getMODIFY_TIME() == null ? other.getMODIFY_TIME() == null : this.getMODIFY_TIME().equals(other.getMODIFY_TIME()))
            && (this.getCREATED_ID() == null ? other.getCREATED_ID() == null : this.getCREATED_ID().equals(other.getCREATED_ID()))
            && (this.getCREATED_TIME() == null ? other.getCREATED_TIME() == null : this.getCREATED_TIME().equals(other.getCREATED_TIME()))
            && (this.getUPDATED_ID() == null ? other.getUPDATED_ID() == null : this.getUPDATED_ID().equals(other.getUPDATED_ID()))
            && (this.getUPDATED_TIME() == null ? other.getUPDATED_TIME() == null : this.getUPDATED_TIME().equals(other.getUPDATED_TIME()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getORG_ID() == null) ? 0 : getORG_ID().hashCode());
        result = prime * result + ((getPARENT_ID() == null) ? 0 : getPARENT_ID().hashCode());
        result = prime * result + ((getTREE_PATH() == null) ? 0 : getTREE_PATH().hashCode());
        result = prime * result + ((getMERCHANT_ID() == null) ? 0 : getMERCHANT_ID().hashCode());
        result = prime * result + ((getSHOP_CODE() == null) ? 0 : getSHOP_CODE().hashCode());
        result = prime * result + ((getSHOP_NAME() == null) ? 0 : getSHOP_NAME().hashCode());
        result = prime * result + ((getSHOP_SHORT_NAME() == null) ? 0 : getSHOP_SHORT_NAME().hashCode());
        result = prime * result + ((getTYPE() == null) ? 0 : getTYPE().hashCode());
        result = prime * result + ((getCOMMISSION_RATE() == null) ? 0 : getCOMMISSION_RATE().hashCode());
        result = prime * result + ((getINDEPENDENT_ACCOUNTING() == null) ? 0 : getINDEPENDENT_ACCOUNTING().hashCode());
        result = prime * result + ((getREGISTERED_BANK() == null) ? 0 : getREGISTERED_BANK().hashCode());
        result = prime * result + ((getACCOUNT_TYPE() == null) ? 0 : getACCOUNT_TYPE().hashCode());
        result = prime * result + ((getACCOUNTING_ACCOUNT_NAME() == null) ? 0 : getACCOUNTING_ACCOUNT_NAME().hashCode());
        result = prime * result + ((getACCOUNTING_ACCOUNT_NO() == null) ? 0 : getACCOUNTING_ACCOUNT_NO().hashCode());
        result = prime * result + ((getONLINE_STATUS() == null) ? 0 : getONLINE_STATUS().hashCode());
        result = prime * result + ((getAPPROVER() == null) ? 0 : getAPPROVER().hashCode());
        result = prime * result + ((getAPPROVAL_REMARK() == null) ? 0 : getAPPROVAL_REMARK().hashCode());
        result = prime * result + ((getAPPROVAL_STATUS() == null) ? 0 : getAPPROVAL_STATUS().hashCode());
        result = prime * result + ((getAPPROVAL_TIME() == null) ? 0 : getAPPROVAL_TIME().hashCode());
        result = prime * result + ((getPROVINCE_ID() == null) ? 0 : getPROVINCE_ID().hashCode());
        result = prime * result + ((getCITY_ID() == null) ? 0 : getCITY_ID().hashCode());
        result = prime * result + ((getDISTRICT_ID() == null) ? 0 : getDISTRICT_ID().hashCode());
        result = prime * result + ((getADDRESS() == null) ? 0 : getADDRESS().hashCode());
        result = prime * result + ((getCONCERN_TYPE() == null) ? 0 : getCONCERN_TYPE().hashCode());
        result = prime * result + ((getBUSINESS_DISTRICT_ID() == null) ? 0 : getBUSINESS_DISTRICT_ID().hashCode());
        result = prime * result + ((getINDUSTRY_ID() == null) ? 0 : getINDUSTRY_ID().hashCode());
        result = prime * result + ((getCONTACT_PERSON() == null) ? 0 : getCONTACT_PERSON().hashCode());
        result = prime * result + ((getCONTACT_PHONE() == null) ? 0 : getCONTACT_PHONE().hashCode());
        result = prime * result + ((getSHOP_INTRODUCTION() == null) ? 0 : getSHOP_INTRODUCTION().hashCode());
        result = prime * result + ((getREMARK() == null) ? 0 : getREMARK().hashCode());
        result = prime * result + ((getURL_SHOP_PIC1() == null) ? 0 : getURL_SHOP_PIC1().hashCode());
        result = prime * result + ((getURL_SHOP_PIC2() == null) ? 0 : getURL_SHOP_PIC2().hashCode());
        result = prime * result + ((getSTATUS() == null) ? 0 : getSTATUS().hashCode());
        result = prime * result + ((getMODIFY_ID() == null) ? 0 : getMODIFY_ID().hashCode());
        result = prime * result + ((getMODIFY_TIME() == null) ? 0 : getMODIFY_TIME().hashCode());
        result = prime * result + ((getCREATED_ID() == null) ? 0 : getCREATED_ID().hashCode());
        result = prime * result + ((getCREATED_TIME() == null) ? 0 : getCREATED_TIME().hashCode());
        result = prime * result + ((getUPDATED_ID() == null) ? 0 : getUPDATED_ID().hashCode());
        result = prime * result + ((getUPDATED_TIME() == null) ? 0 : getUPDATED_TIME().hashCode());
        return result;
    }
}