package org.ipay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class T_merchant implements Serializable {
    /**
     * 表 : T_MERCHANT
     * 对应字段 : ID
     */
    private Long ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : REQ_SEQ_NO
     */
    private String REQ_SEQ_NO;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : TOP_ORG_ID
     */
    private BigDecimal TOP_ORG_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ORG_ID
     */
    private BigDecimal ORG_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : DEPARTMENT_ID
     */
    private BigDecimal DEPARTMENT_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : MERCHANT_CODE
     */
    private String MERCHANT_CODE;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : MERCHANT_NAME
     */
    private String MERCHANT_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : MERCHANT_SHORT_NAME
     */
    private String MERCHANT_SHORT_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : AGENTS_ID
     */
    private BigDecimal AGENTS_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : CUSTOMER_MANAGER
     */
    private String CUSTOMER_MANAGER;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : CUSTOMER_MANAGER_NAME
     */
    private String CUSTOMER_MANAGER_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : CUSTOMER_MANAGER_CODE
     */
    private String CUSTOMER_MANAGER_CODE;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ENABLED_STATUS
     */
    private String ENABLED_STATUS;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ENABLED_USER
     */
    private String ENABLED_USER;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ENABLED_TIME
     */
    private Date ENABLED_TIME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : APPROVAL_STATUS
     */
    private String APPROVAL_STATUS;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : APPROVAL_REMARK
     */
    private String APPROVAL_REMARK;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : APPROVER
     */
    private String APPROVER;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : APPROVER_NAME
     */
    private String APPROVER_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : APPROVER_CODE
     */
    private String APPROVER_CODE;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : APPROVAL_TIME
     */
    private Date APPROVAL_TIME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ACTIVE_STATUS
     */
    private String ACTIVE_STATUS;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ACTIVE_REMARK
     */
    private String ACTIVE_REMARK;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ACTIVE_USER
     */
    private String ACTIVE_USER;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ACTIVE_NAME
     */
    private String ACTIVE_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ACTIVE_CODE
     */
    private String ACTIVE_CODE;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ACTIVE_TIME
     */
    private Date ACTIVE_TIME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : RECORD_STATUS
     */
    private String RECORD_STATUS;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : MODIFY_ID
     */
    private BigDecimal MODIFY_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : MODIFY_NAME
     */
    private String MODIFY_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : MODIFY_CODE
     */
    private String MODIFY_CODE;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : MODIFY_TIME
     */
    private Date MODIFY_TIME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : ORIGIN_ID
     */
    private BigDecimal ORIGIN_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : INPUT_WAY_ID
     */
    private BigDecimal INPUT_WAY_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : CREATED_ID
     */
    private BigDecimal CREATED_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : CREATED_NAME
     */
    private String CREATED_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : CREATED_CODE
     */
    private String CREATED_CODE;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : CREATED_TIME
     */
    private Date CREATED_TIME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : UPDATED_ID
     */
    private BigDecimal UPDATED_ID;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : UPDATED_NAME
     */
    private String UPDATED_NAME;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : UPDATED_CODE
     */
    private String UPDATED_CODE;

    /**
     * 表 : T_MERCHANT
     * 对应字段 : UPDATED_TIME
     */
    private Date UPDATED_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MERCHANT
     *
     * @MBG Generated Fri Sep 01 15:32:59 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return T_MERCHANT.ID：null
     */
    public Long getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.REQ_SEQ_NO：null
     */
    public String getREQ_SEQ_NO() {
        return REQ_SEQ_NO;
    }

    /**
     * set method 
     *
     * @param REQ_SEQ_NO  null
     */
    public void setREQ_SEQ_NO(String REQ_SEQ_NO) {
        this.REQ_SEQ_NO = REQ_SEQ_NO == null ? null : REQ_SEQ_NO.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.TOP_ORG_ID：null
     */
    public BigDecimal getTOP_ORG_ID() {
        return TOP_ORG_ID;
    }

    /**
     * set method 
     *
     * @param TOP_ORG_ID  null
     */
    public void setTOP_ORG_ID(BigDecimal TOP_ORG_ID) {
        this.TOP_ORG_ID = TOP_ORG_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ORG_ID：null
     */
    public BigDecimal getORG_ID() {
        return ORG_ID;
    }

    /**
     * set method 
     *
     * @param ORG_ID  null
     */
    public void setORG_ID(BigDecimal ORG_ID) {
        this.ORG_ID = ORG_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.DEPARTMENT_ID：null
     */
    public BigDecimal getDEPARTMENT_ID() {
        return DEPARTMENT_ID;
    }

    /**
     * set method 
     *
     * @param DEPARTMENT_ID  null
     */
    public void setDEPARTMENT_ID(BigDecimal DEPARTMENT_ID) {
        this.DEPARTMENT_ID = DEPARTMENT_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.MERCHANT_CODE：null
     */
    public String getMERCHANT_CODE() {
        return MERCHANT_CODE;
    }

    /**
     * set method 
     *
     * @param MERCHANT_CODE  null
     */
    public void setMERCHANT_CODE(String MERCHANT_CODE) {
        this.MERCHANT_CODE = MERCHANT_CODE == null ? null : MERCHANT_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.MERCHANT_NAME：null
     */
    public String getMERCHANT_NAME() {
        return MERCHANT_NAME;
    }

    /**
     * set method 
     *
     * @param MERCHANT_NAME  null
     */
    public void setMERCHANT_NAME(String MERCHANT_NAME) {
        this.MERCHANT_NAME = MERCHANT_NAME == null ? null : MERCHANT_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.MERCHANT_SHORT_NAME：null
     */
    public String getMERCHANT_SHORT_NAME() {
        return MERCHANT_SHORT_NAME;
    }

    /**
     * set method 
     *
     * @param MERCHANT_SHORT_NAME  null
     */
    public void setMERCHANT_SHORT_NAME(String MERCHANT_SHORT_NAME) {
        this.MERCHANT_SHORT_NAME = MERCHANT_SHORT_NAME == null ? null : MERCHANT_SHORT_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.AGENTS_ID：null
     */
    public BigDecimal getAGENTS_ID() {
        return AGENTS_ID;
    }

    /**
     * set method 
     *
     * @param AGENTS_ID  null
     */
    public void setAGENTS_ID(BigDecimal AGENTS_ID) {
        this.AGENTS_ID = AGENTS_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.CUSTOMER_MANAGER：null
     */
    public String getCUSTOMER_MANAGER() {
        return CUSTOMER_MANAGER;
    }

    /**
     * set method 
     *
     * @param CUSTOMER_MANAGER  null
     */
    public void setCUSTOMER_MANAGER(String CUSTOMER_MANAGER) {
        this.CUSTOMER_MANAGER = CUSTOMER_MANAGER == null ? null : CUSTOMER_MANAGER.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.CUSTOMER_MANAGER_NAME：null
     */
    public String getCUSTOMER_MANAGER_NAME() {
        return CUSTOMER_MANAGER_NAME;
    }

    /**
     * set method 
     *
     * @param CUSTOMER_MANAGER_NAME  null
     */
    public void setCUSTOMER_MANAGER_NAME(String CUSTOMER_MANAGER_NAME) {
        this.CUSTOMER_MANAGER_NAME = CUSTOMER_MANAGER_NAME == null ? null : CUSTOMER_MANAGER_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.CUSTOMER_MANAGER_CODE：null
     */
    public String getCUSTOMER_MANAGER_CODE() {
        return CUSTOMER_MANAGER_CODE;
    }

    /**
     * set method 
     *
     * @param CUSTOMER_MANAGER_CODE  null
     */
    public void setCUSTOMER_MANAGER_CODE(String CUSTOMER_MANAGER_CODE) {
        this.CUSTOMER_MANAGER_CODE = CUSTOMER_MANAGER_CODE == null ? null : CUSTOMER_MANAGER_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ENABLED_STATUS：null
     */
    public String getENABLED_STATUS() {
        return ENABLED_STATUS;
    }

    /**
     * set method 
     *
     * @param ENABLED_STATUS  null
     */
    public void setENABLED_STATUS(String ENABLED_STATUS) {
        this.ENABLED_STATUS = ENABLED_STATUS == null ? null : ENABLED_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ENABLED_USER：null
     */
    public String getENABLED_USER() {
        return ENABLED_USER;
    }

    /**
     * set method 
     *
     * @param ENABLED_USER  null
     */
    public void setENABLED_USER(String ENABLED_USER) {
        this.ENABLED_USER = ENABLED_USER == null ? null : ENABLED_USER.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ENABLED_TIME：null
     */
    public Date getENABLED_TIME() {
        return ENABLED_TIME;
    }

    /**
     * set method 
     *
     * @param ENABLED_TIME  null
     */
    public void setENABLED_TIME(Date ENABLED_TIME) {
        this.ENABLED_TIME = ENABLED_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.APPROVAL_STATUS：null
     */
    public String getAPPROVAL_STATUS() {
        return APPROVAL_STATUS;
    }

    /**
     * set method 
     *
     * @param APPROVAL_STATUS  null
     */
    public void setAPPROVAL_STATUS(String APPROVAL_STATUS) {
        this.APPROVAL_STATUS = APPROVAL_STATUS == null ? null : APPROVAL_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.APPROVAL_REMARK：null
     */
    public String getAPPROVAL_REMARK() {
        return APPROVAL_REMARK;
    }

    /**
     * set method 
     *
     * @param APPROVAL_REMARK  null
     */
    public void setAPPROVAL_REMARK(String APPROVAL_REMARK) {
        this.APPROVAL_REMARK = APPROVAL_REMARK == null ? null : APPROVAL_REMARK.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.APPROVER：null
     */
    public String getAPPROVER() {
        return APPROVER;
    }

    /**
     * set method 
     *
     * @param APPROVER  null
     */
    public void setAPPROVER(String APPROVER) {
        this.APPROVER = APPROVER == null ? null : APPROVER.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.APPROVER_NAME：null
     */
    public String getAPPROVER_NAME() {
        return APPROVER_NAME;
    }

    /**
     * set method 
     *
     * @param APPROVER_NAME  null
     */
    public void setAPPROVER_NAME(String APPROVER_NAME) {
        this.APPROVER_NAME = APPROVER_NAME == null ? null : APPROVER_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.APPROVER_CODE：null
     */
    public String getAPPROVER_CODE() {
        return APPROVER_CODE;
    }

    /**
     * set method 
     *
     * @param APPROVER_CODE  null
     */
    public void setAPPROVER_CODE(String APPROVER_CODE) {
        this.APPROVER_CODE = APPROVER_CODE == null ? null : APPROVER_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.APPROVAL_TIME：null
     */
    public Date getAPPROVAL_TIME() {
        return APPROVAL_TIME;
    }

    /**
     * set method 
     *
     * @param APPROVAL_TIME  null
     */
    public void setAPPROVAL_TIME(Date APPROVAL_TIME) {
        this.APPROVAL_TIME = APPROVAL_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ACTIVE_STATUS：null
     */
    public String getACTIVE_STATUS() {
        return ACTIVE_STATUS;
    }

    /**
     * set method 
     *
     * @param ACTIVE_STATUS  null
     */
    public void setACTIVE_STATUS(String ACTIVE_STATUS) {
        this.ACTIVE_STATUS = ACTIVE_STATUS == null ? null : ACTIVE_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ACTIVE_REMARK：null
     */
    public String getACTIVE_REMARK() {
        return ACTIVE_REMARK;
    }

    /**
     * set method 
     *
     * @param ACTIVE_REMARK  null
     */
    public void setACTIVE_REMARK(String ACTIVE_REMARK) {
        this.ACTIVE_REMARK = ACTIVE_REMARK == null ? null : ACTIVE_REMARK.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ACTIVE_USER：null
     */
    public String getACTIVE_USER() {
        return ACTIVE_USER;
    }

    /**
     * set method 
     *
     * @param ACTIVE_USER  null
     */
    public void setACTIVE_USER(String ACTIVE_USER) {
        this.ACTIVE_USER = ACTIVE_USER == null ? null : ACTIVE_USER.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ACTIVE_NAME：null
     */
    public String getACTIVE_NAME() {
        return ACTIVE_NAME;
    }

    /**
     * set method 
     *
     * @param ACTIVE_NAME  null
     */
    public void setACTIVE_NAME(String ACTIVE_NAME) {
        this.ACTIVE_NAME = ACTIVE_NAME == null ? null : ACTIVE_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ACTIVE_CODE：null
     */
    public String getACTIVE_CODE() {
        return ACTIVE_CODE;
    }

    /**
     * set method 
     *
     * @param ACTIVE_CODE  null
     */
    public void setACTIVE_CODE(String ACTIVE_CODE) {
        this.ACTIVE_CODE = ACTIVE_CODE == null ? null : ACTIVE_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ACTIVE_TIME：null
     */
    public Date getACTIVE_TIME() {
        return ACTIVE_TIME;
    }

    /**
     * set method 
     *
     * @param ACTIVE_TIME  null
     */
    public void setACTIVE_TIME(Date ACTIVE_TIME) {
        this.ACTIVE_TIME = ACTIVE_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.RECORD_STATUS：null
     */
    public String getRECORD_STATUS() {
        return RECORD_STATUS;
    }

    /**
     * set method 
     *
     * @param RECORD_STATUS  null
     */
    public void setRECORD_STATUS(String RECORD_STATUS) {
        this.RECORD_STATUS = RECORD_STATUS == null ? null : RECORD_STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.MODIFY_ID：null
     */
    public BigDecimal getMODIFY_ID() {
        return MODIFY_ID;
    }

    /**
     * set method 
     *
     * @param MODIFY_ID  null
     */
    public void setMODIFY_ID(BigDecimal MODIFY_ID) {
        this.MODIFY_ID = MODIFY_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.MODIFY_NAME：null
     */
    public String getMODIFY_NAME() {
        return MODIFY_NAME;
    }

    /**
     * set method 
     *
     * @param MODIFY_NAME  null
     */
    public void setMODIFY_NAME(String MODIFY_NAME) {
        this.MODIFY_NAME = MODIFY_NAME == null ? null : MODIFY_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.MODIFY_CODE：null
     */
    public String getMODIFY_CODE() {
        return MODIFY_CODE;
    }

    /**
     * set method 
     *
     * @param MODIFY_CODE  null
     */
    public void setMODIFY_CODE(String MODIFY_CODE) {
        this.MODIFY_CODE = MODIFY_CODE == null ? null : MODIFY_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.MODIFY_TIME：null
     */
    public Date getMODIFY_TIME() {
        return MODIFY_TIME;
    }

    /**
     * set method 
     *
     * @param MODIFY_TIME  null
     */
    public void setMODIFY_TIME(Date MODIFY_TIME) {
        this.MODIFY_TIME = MODIFY_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.ORIGIN_ID：null
     */
    public BigDecimal getORIGIN_ID() {
        return ORIGIN_ID;
    }

    /**
     * set method 
     *
     * @param ORIGIN_ID  null
     */
    public void setORIGIN_ID(BigDecimal ORIGIN_ID) {
        this.ORIGIN_ID = ORIGIN_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.INPUT_WAY_ID：null
     */
    public BigDecimal getINPUT_WAY_ID() {
        return INPUT_WAY_ID;
    }

    /**
     * set method 
     *
     * @param INPUT_WAY_ID  null
     */
    public void setINPUT_WAY_ID(BigDecimal INPUT_WAY_ID) {
        this.INPUT_WAY_ID = INPUT_WAY_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.CREATED_ID：null
     */
    public BigDecimal getCREATED_ID() {
        return CREATED_ID;
    }

    /**
     * set method 
     *
     * @param CREATED_ID  null
     */
    public void setCREATED_ID(BigDecimal CREATED_ID) {
        this.CREATED_ID = CREATED_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.CREATED_NAME：null
     */
    public String getCREATED_NAME() {
        return CREATED_NAME;
    }

    /**
     * set method 
     *
     * @param CREATED_NAME  null
     */
    public void setCREATED_NAME(String CREATED_NAME) {
        this.CREATED_NAME = CREATED_NAME == null ? null : CREATED_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.CREATED_CODE：null
     */
    public String getCREATED_CODE() {
        return CREATED_CODE;
    }

    /**
     * set method 
     *
     * @param CREATED_CODE  null
     */
    public void setCREATED_CODE(String CREATED_CODE) {
        this.CREATED_CODE = CREATED_CODE == null ? null : CREATED_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.CREATED_TIME：null
     */
    public Date getCREATED_TIME() {
        return CREATED_TIME;
    }

    /**
     * set method 
     *
     * @param CREATED_TIME  null
     */
    public void setCREATED_TIME(Date CREATED_TIME) {
        this.CREATED_TIME = CREATED_TIME;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.UPDATED_ID：null
     */
    public BigDecimal getUPDATED_ID() {
        return UPDATED_ID;
    }

    /**
     * set method 
     *
     * @param UPDATED_ID  null
     */
    public void setUPDATED_ID(BigDecimal UPDATED_ID) {
        this.UPDATED_ID = UPDATED_ID;
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.UPDATED_NAME：null
     */
    public String getUPDATED_NAME() {
        return UPDATED_NAME;
    }

    /**
     * set method 
     *
     * @param UPDATED_NAME  null
     */
    public void setUPDATED_NAME(String UPDATED_NAME) {
        this.UPDATED_NAME = UPDATED_NAME == null ? null : UPDATED_NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.UPDATED_CODE：null
     */
    public String getUPDATED_CODE() {
        return UPDATED_CODE;
    }

    /**
     * set method 
     *
     * @param UPDATED_CODE  null
     */
    public void setUPDATED_CODE(String UPDATED_CODE) {
        this.UPDATED_CODE = UPDATED_CODE == null ? null : UPDATED_CODE.trim();
    }

    /**
     * get method 
     *
     * @return T_MERCHANT.UPDATED_TIME：null
     */
    public Date getUPDATED_TIME() {
        return UPDATED_TIME;
    }

    /**
     * set method 
     *
     * @param UPDATED_TIME  null
     */
    public void setUPDATED_TIME(Date UPDATED_TIME) {
        this.UPDATED_TIME = UPDATED_TIME;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T_merchant other = (T_merchant) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getREQ_SEQ_NO() == null ? other.getREQ_SEQ_NO() == null : this.getREQ_SEQ_NO().equals(other.getREQ_SEQ_NO()))
            && (this.getTOP_ORG_ID() == null ? other.getTOP_ORG_ID() == null : this.getTOP_ORG_ID().equals(other.getTOP_ORG_ID()))
            && (this.getORG_ID() == null ? other.getORG_ID() == null : this.getORG_ID().equals(other.getORG_ID()))
            && (this.getDEPARTMENT_ID() == null ? other.getDEPARTMENT_ID() == null : this.getDEPARTMENT_ID().equals(other.getDEPARTMENT_ID()))
            && (this.getMERCHANT_CODE() == null ? other.getMERCHANT_CODE() == null : this.getMERCHANT_CODE().equals(other.getMERCHANT_CODE()))
            && (this.getMERCHANT_NAME() == null ? other.getMERCHANT_NAME() == null : this.getMERCHANT_NAME().equals(other.getMERCHANT_NAME()))
            && (this.getMERCHANT_SHORT_NAME() == null ? other.getMERCHANT_SHORT_NAME() == null : this.getMERCHANT_SHORT_NAME().equals(other.getMERCHANT_SHORT_NAME()))
            && (this.getAGENTS_ID() == null ? other.getAGENTS_ID() == null : this.getAGENTS_ID().equals(other.getAGENTS_ID()))
            && (this.getCUSTOMER_MANAGER() == null ? other.getCUSTOMER_MANAGER() == null : this.getCUSTOMER_MANAGER().equals(other.getCUSTOMER_MANAGER()))
            && (this.getCUSTOMER_MANAGER_NAME() == null ? other.getCUSTOMER_MANAGER_NAME() == null : this.getCUSTOMER_MANAGER_NAME().equals(other.getCUSTOMER_MANAGER_NAME()))
            && (this.getCUSTOMER_MANAGER_CODE() == null ? other.getCUSTOMER_MANAGER_CODE() == null : this.getCUSTOMER_MANAGER_CODE().equals(other.getCUSTOMER_MANAGER_CODE()))
            && (this.getENABLED_STATUS() == null ? other.getENABLED_STATUS() == null : this.getENABLED_STATUS().equals(other.getENABLED_STATUS()))
            && (this.getENABLED_USER() == null ? other.getENABLED_USER() == null : this.getENABLED_USER().equals(other.getENABLED_USER()))
            && (this.getENABLED_TIME() == null ? other.getENABLED_TIME() == null : this.getENABLED_TIME().equals(other.getENABLED_TIME()))
            && (this.getAPPROVAL_STATUS() == null ? other.getAPPROVAL_STATUS() == null : this.getAPPROVAL_STATUS().equals(other.getAPPROVAL_STATUS()))
            && (this.getAPPROVAL_REMARK() == null ? other.getAPPROVAL_REMARK() == null : this.getAPPROVAL_REMARK().equals(other.getAPPROVAL_REMARK()))
            && (this.getAPPROVER() == null ? other.getAPPROVER() == null : this.getAPPROVER().equals(other.getAPPROVER()))
            && (this.getAPPROVER_NAME() == null ? other.getAPPROVER_NAME() == null : this.getAPPROVER_NAME().equals(other.getAPPROVER_NAME()))
            && (this.getAPPROVER_CODE() == null ? other.getAPPROVER_CODE() == null : this.getAPPROVER_CODE().equals(other.getAPPROVER_CODE()))
            && (this.getAPPROVAL_TIME() == null ? other.getAPPROVAL_TIME() == null : this.getAPPROVAL_TIME().equals(other.getAPPROVAL_TIME()))
            && (this.getACTIVE_STATUS() == null ? other.getACTIVE_STATUS() == null : this.getACTIVE_STATUS().equals(other.getACTIVE_STATUS()))
            && (this.getACTIVE_REMARK() == null ? other.getACTIVE_REMARK() == null : this.getACTIVE_REMARK().equals(other.getACTIVE_REMARK()))
            && (this.getACTIVE_USER() == null ? other.getACTIVE_USER() == null : this.getACTIVE_USER().equals(other.getACTIVE_USER()))
            && (this.getACTIVE_NAME() == null ? other.getACTIVE_NAME() == null : this.getACTIVE_NAME().equals(other.getACTIVE_NAME()))
            && (this.getACTIVE_CODE() == null ? other.getACTIVE_CODE() == null : this.getACTIVE_CODE().equals(other.getACTIVE_CODE()))
            && (this.getACTIVE_TIME() == null ? other.getACTIVE_TIME() == null : this.getACTIVE_TIME().equals(other.getACTIVE_TIME()))
            && (this.getRECORD_STATUS() == null ? other.getRECORD_STATUS() == null : this.getRECORD_STATUS().equals(other.getRECORD_STATUS()))
            && (this.getMODIFY_ID() == null ? other.getMODIFY_ID() == null : this.getMODIFY_ID().equals(other.getMODIFY_ID()))
            && (this.getMODIFY_NAME() == null ? other.getMODIFY_NAME() == null : this.getMODIFY_NAME().equals(other.getMODIFY_NAME()))
            && (this.getMODIFY_CODE() == null ? other.getMODIFY_CODE() == null : this.getMODIFY_CODE().equals(other.getMODIFY_CODE()))
            && (this.getMODIFY_TIME() == null ? other.getMODIFY_TIME() == null : this.getMODIFY_TIME().equals(other.getMODIFY_TIME()))
            && (this.getORIGIN_ID() == null ? other.getORIGIN_ID() == null : this.getORIGIN_ID().equals(other.getORIGIN_ID()))
            && (this.getINPUT_WAY_ID() == null ? other.getINPUT_WAY_ID() == null : this.getINPUT_WAY_ID().equals(other.getINPUT_WAY_ID()))
            && (this.getCREATED_ID() == null ? other.getCREATED_ID() == null : this.getCREATED_ID().equals(other.getCREATED_ID()))
            && (this.getCREATED_NAME() == null ? other.getCREATED_NAME() == null : this.getCREATED_NAME().equals(other.getCREATED_NAME()))
            && (this.getCREATED_CODE() == null ? other.getCREATED_CODE() == null : this.getCREATED_CODE().equals(other.getCREATED_CODE()))
            && (this.getCREATED_TIME() == null ? other.getCREATED_TIME() == null : this.getCREATED_TIME().equals(other.getCREATED_TIME()))
            && (this.getUPDATED_ID() == null ? other.getUPDATED_ID() == null : this.getUPDATED_ID().equals(other.getUPDATED_ID()))
            && (this.getUPDATED_NAME() == null ? other.getUPDATED_NAME() == null : this.getUPDATED_NAME().equals(other.getUPDATED_NAME()))
            && (this.getUPDATED_CODE() == null ? other.getUPDATED_CODE() == null : this.getUPDATED_CODE().equals(other.getUPDATED_CODE()))
            && (this.getUPDATED_TIME() == null ? other.getUPDATED_TIME() == null : this.getUPDATED_TIME().equals(other.getUPDATED_TIME()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getREQ_SEQ_NO() == null) ? 0 : getREQ_SEQ_NO().hashCode());
        result = prime * result + ((getTOP_ORG_ID() == null) ? 0 : getTOP_ORG_ID().hashCode());
        result = prime * result + ((getORG_ID() == null) ? 0 : getORG_ID().hashCode());
        result = prime * result + ((getDEPARTMENT_ID() == null) ? 0 : getDEPARTMENT_ID().hashCode());
        result = prime * result + ((getMERCHANT_CODE() == null) ? 0 : getMERCHANT_CODE().hashCode());
        result = prime * result + ((getMERCHANT_NAME() == null) ? 0 : getMERCHANT_NAME().hashCode());
        result = prime * result + ((getMERCHANT_SHORT_NAME() == null) ? 0 : getMERCHANT_SHORT_NAME().hashCode());
        result = prime * result + ((getAGENTS_ID() == null) ? 0 : getAGENTS_ID().hashCode());
        result = prime * result + ((getCUSTOMER_MANAGER() == null) ? 0 : getCUSTOMER_MANAGER().hashCode());
        result = prime * result + ((getCUSTOMER_MANAGER_NAME() == null) ? 0 : getCUSTOMER_MANAGER_NAME().hashCode());
        result = prime * result + ((getCUSTOMER_MANAGER_CODE() == null) ? 0 : getCUSTOMER_MANAGER_CODE().hashCode());
        result = prime * result + ((getENABLED_STATUS() == null) ? 0 : getENABLED_STATUS().hashCode());
        result = prime * result + ((getENABLED_USER() == null) ? 0 : getENABLED_USER().hashCode());
        result = prime * result + ((getENABLED_TIME() == null) ? 0 : getENABLED_TIME().hashCode());
        result = prime * result + ((getAPPROVAL_STATUS() == null) ? 0 : getAPPROVAL_STATUS().hashCode());
        result = prime * result + ((getAPPROVAL_REMARK() == null) ? 0 : getAPPROVAL_REMARK().hashCode());
        result = prime * result + ((getAPPROVER() == null) ? 0 : getAPPROVER().hashCode());
        result = prime * result + ((getAPPROVER_NAME() == null) ? 0 : getAPPROVER_NAME().hashCode());
        result = prime * result + ((getAPPROVER_CODE() == null) ? 0 : getAPPROVER_CODE().hashCode());
        result = prime * result + ((getAPPROVAL_TIME() == null) ? 0 : getAPPROVAL_TIME().hashCode());
        result = prime * result + ((getACTIVE_STATUS() == null) ? 0 : getACTIVE_STATUS().hashCode());
        result = prime * result + ((getACTIVE_REMARK() == null) ? 0 : getACTIVE_REMARK().hashCode());
        result = prime * result + ((getACTIVE_USER() == null) ? 0 : getACTIVE_USER().hashCode());
        result = prime * result + ((getACTIVE_NAME() == null) ? 0 : getACTIVE_NAME().hashCode());
        result = prime * result + ((getACTIVE_CODE() == null) ? 0 : getACTIVE_CODE().hashCode());
        result = prime * result + ((getACTIVE_TIME() == null) ? 0 : getACTIVE_TIME().hashCode());
        result = prime * result + ((getRECORD_STATUS() == null) ? 0 : getRECORD_STATUS().hashCode());
        result = prime * result + ((getMODIFY_ID() == null) ? 0 : getMODIFY_ID().hashCode());
        result = prime * result + ((getMODIFY_NAME() == null) ? 0 : getMODIFY_NAME().hashCode());
        result = prime * result + ((getMODIFY_CODE() == null) ? 0 : getMODIFY_CODE().hashCode());
        result = prime * result + ((getMODIFY_TIME() == null) ? 0 : getMODIFY_TIME().hashCode());
        result = prime * result + ((getORIGIN_ID() == null) ? 0 : getORIGIN_ID().hashCode());
        result = prime * result + ((getINPUT_WAY_ID() == null) ? 0 : getINPUT_WAY_ID().hashCode());
        result = prime * result + ((getCREATED_ID() == null) ? 0 : getCREATED_ID().hashCode());
        result = prime * result + ((getCREATED_NAME() == null) ? 0 : getCREATED_NAME().hashCode());
        result = prime * result + ((getCREATED_CODE() == null) ? 0 : getCREATED_CODE().hashCode());
        result = prime * result + ((getCREATED_TIME() == null) ? 0 : getCREATED_TIME().hashCode());
        result = prime * result + ((getUPDATED_ID() == null) ? 0 : getUPDATED_ID().hashCode());
        result = prime * result + ((getUPDATED_NAME() == null) ? 0 : getUPDATED_NAME().hashCode());
        result = prime * result + ((getUPDATED_CODE() == null) ? 0 : getUPDATED_CODE().hashCode());
        result = prime * result + ((getUPDATED_TIME() == null) ? 0 : getUPDATED_TIME().hashCode());
        return result;
    }
}