package org.ipay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class T_rate_template_type implements Serializable {
    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : ID
     */
    private Long ID;

    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : NAME
     */
    private String NAME;

    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : TOP_ORG_ID
     */
    private BigDecimal TOP_ORG_ID;

    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : STATUS
     */
    private String STATUS;

    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : CREATED_ID
     */
    private BigDecimal CREATED_ID;

    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : CREATED_TIME
     */
    private Date CREATED_TIME;

    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : UPDATED_ID
     */
    private BigDecimal UPDATED_ID;

    /**
     * 表 : T_RATE_TEMPLATE_TYPE
     * 对应字段 : UPDATED_TIME
     */
    private Date UPDATED_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_RATE_TEMPLATE_TYPE
     *
     * @MBG Generated Tue Sep 05 11:44:25 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.ID：null
     */
    public Long getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.NAME：null
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * set method 
     *
     * @param NAME  null
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.TOP_ORG_ID：null
     */
    public BigDecimal getTOP_ORG_ID() {
        return TOP_ORG_ID;
    }

    /**
     * set method 
     *
     * @param TOP_ORG_ID  null
     */
    public void setTOP_ORG_ID(BigDecimal TOP_ORG_ID) {
        this.TOP_ORG_ID = TOP_ORG_ID;
    }

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.STATUS：null
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * set method 
     *
     * @param STATUS  null
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.CREATED_ID：null
     */
    public BigDecimal getCREATED_ID() {
        return CREATED_ID;
    }

    /**
     * set method 
     *
     * @param CREATED_ID  null
     */
    public void setCREATED_ID(BigDecimal CREATED_ID) {
        this.CREATED_ID = CREATED_ID;
    }

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.CREATED_TIME：null
     */
    public Date getCREATED_TIME() {
        return CREATED_TIME;
    }

    /**
     * set method 
     *
     * @param CREATED_TIME  null
     */
    public void setCREATED_TIME(Date CREATED_TIME) {
        this.CREATED_TIME = CREATED_TIME;
    }

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.UPDATED_ID：null
     */
    public BigDecimal getUPDATED_ID() {
        return UPDATED_ID;
    }

    /**
     * set method 
     *
     * @param UPDATED_ID  null
     */
    public void setUPDATED_ID(BigDecimal UPDATED_ID) {
        this.UPDATED_ID = UPDATED_ID;
    }

    /**
     * get method 
     *
     * @return T_RATE_TEMPLATE_TYPE.UPDATED_TIME：null
     */
    public Date getUPDATED_TIME() {
        return UPDATED_TIME;
    }

    /**
     * set method 
     *
     * @param UPDATED_TIME  null
     */
    public void setUPDATED_TIME(Date UPDATED_TIME) {
        this.UPDATED_TIME = UPDATED_TIME;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T_rate_template_type other = (T_rate_template_type) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getNAME() == null ? other.getNAME() == null : this.getNAME().equals(other.getNAME()))
            && (this.getTOP_ORG_ID() == null ? other.getTOP_ORG_ID() == null : this.getTOP_ORG_ID().equals(other.getTOP_ORG_ID()))
            && (this.getSTATUS() == null ? other.getSTATUS() == null : this.getSTATUS().equals(other.getSTATUS()))
            && (this.getCREATED_ID() == null ? other.getCREATED_ID() == null : this.getCREATED_ID().equals(other.getCREATED_ID()))
            && (this.getCREATED_TIME() == null ? other.getCREATED_TIME() == null : this.getCREATED_TIME().equals(other.getCREATED_TIME()))
            && (this.getUPDATED_ID() == null ? other.getUPDATED_ID() == null : this.getUPDATED_ID().equals(other.getUPDATED_ID()))
            && (this.getUPDATED_TIME() == null ? other.getUPDATED_TIME() == null : this.getUPDATED_TIME().equals(other.getUPDATED_TIME()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getNAME() == null) ? 0 : getNAME().hashCode());
        result = prime * result + ((getTOP_ORG_ID() == null) ? 0 : getTOP_ORG_ID().hashCode());
        result = prime * result + ((getSTATUS() == null) ? 0 : getSTATUS().hashCode());
        result = prime * result + ((getCREATED_ID() == null) ? 0 : getCREATED_ID().hashCode());
        result = prime * result + ((getCREATED_TIME() == null) ? 0 : getCREATED_TIME().hashCode());
        result = prime * result + ((getUPDATED_ID() == null) ? 0 : getUPDATED_ID().hashCode());
        result = prime * result + ((getUPDATED_TIME() == null) ? 0 : getUPDATED_TIME().hashCode());
        return result;
    }
}