package org.ipay.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class T_risk implements Serializable {
    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : ID
     */
    private BigDecimal ID;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : ORDER_ID
     */
    private BigDecimal ORDER_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : BWL_ID
     */
    private BigDecimal BWL_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : STATUS
     */
    private String STATUS;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : REMARKS
     */
    private String REMARKS;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : SIGN
     */
    private String SIGN;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : CREATED_ID
     */
    private BigDecimal CREATED_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : CREATED_TIME
     */
    private Date CREATED_TIME;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : UPDATED_ID
     */
    private BigDecimal UPDATED_ID;

    /**
     * 表 : IPAY_CORE_TEST.T_RISK
     * 对应字段 : UPDATED_TIME
     */
    private Date UPDATED_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IPAY_CORE_TEST.T_RISK
     *
     * @MBG Generated Mon Aug 07 19:43:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.ID：null
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * set method 
     *
     * @param ID  null
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.ORDER_ID：null
     */
    public BigDecimal getORDER_ID() {
        return ORDER_ID;
    }

    /**
     * set method 
     *
     * @param ORDER_ID  null
     */
    public void setORDER_ID(BigDecimal ORDER_ID) {
        this.ORDER_ID = ORDER_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.BWL_ID：null
     */
    public BigDecimal getBWL_ID() {
        return BWL_ID;
    }

    /**
     * set method 
     *
     * @param BWL_ID  null
     */
    public void setBWL_ID(BigDecimal BWL_ID) {
        this.BWL_ID = BWL_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.STATUS：null
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * set method 
     *
     * @param STATUS  null
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.REMARKS：null
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * set method 
     *
     * @param REMARKS  null
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.SIGN：null
     */
    public String getSIGN() {
        return SIGN;
    }

    /**
     * set method 
     *
     * @param SIGN  null
     */
    public void setSIGN(String SIGN) {
        this.SIGN = SIGN == null ? null : SIGN.trim();
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.CREATED_ID：null
     */
    public BigDecimal getCREATED_ID() {
        return CREATED_ID;
    }

    /**
     * set method 
     *
     * @param CREATED_ID  null
     */
    public void setCREATED_ID(BigDecimal CREATED_ID) {
        this.CREATED_ID = CREATED_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.CREATED_TIME：null
     */
    public Date getCREATED_TIME() {
        return CREATED_TIME;
    }

    /**
     * set method 
     *
     * @param CREATED_TIME  null
     */
    public void setCREATED_TIME(Date CREATED_TIME) {
        this.CREATED_TIME = CREATED_TIME;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.UPDATED_ID：null
     */
    public BigDecimal getUPDATED_ID() {
        return UPDATED_ID;
    }

    /**
     * set method 
     *
     * @param UPDATED_ID  null
     */
    public void setUPDATED_ID(BigDecimal UPDATED_ID) {
        this.UPDATED_ID = UPDATED_ID;
    }

    /**
     * get method 
     *
     * @return IPAY_CORE_TEST.T_RISK.UPDATED_TIME：null
     */
    public Date getUPDATED_TIME() {
        return UPDATED_TIME;
    }

    /**
     * set method 
     *
     * @param UPDATED_TIME  null
     */
    public void setUPDATED_TIME(Date UPDATED_TIME) {
        this.UPDATED_TIME = UPDATED_TIME;
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        T_risk other = (T_risk) that;
        return (this.getID() == null ? other.getID() == null : this.getID().equals(other.getID()))
            && (this.getORDER_ID() == null ? other.getORDER_ID() == null : this.getORDER_ID().equals(other.getORDER_ID()))
            && (this.getBWL_ID() == null ? other.getBWL_ID() == null : this.getBWL_ID().equals(other.getBWL_ID()))
            && (this.getSTATUS() == null ? other.getSTATUS() == null : this.getSTATUS().equals(other.getSTATUS()))
            && (this.getREMARKS() == null ? other.getREMARKS() == null : this.getREMARKS().equals(other.getREMARKS()))
            && (this.getSIGN() == null ? other.getSIGN() == null : this.getSIGN().equals(other.getSIGN()))
            && (this.getCREATED_ID() == null ? other.getCREATED_ID() == null : this.getCREATED_ID().equals(other.getCREATED_ID()))
            && (this.getCREATED_TIME() == null ? other.getCREATED_TIME() == null : this.getCREATED_TIME().equals(other.getCREATED_TIME()))
            && (this.getUPDATED_ID() == null ? other.getUPDATED_ID() == null : this.getUPDATED_ID().equals(other.getUPDATED_ID()))
            && (this.getUPDATED_TIME() == null ? other.getUPDATED_TIME() == null : this.getUPDATED_TIME().equals(other.getUPDATED_TIME()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getID() == null) ? 0 : getID().hashCode());
        result = prime * result + ((getORDER_ID() == null) ? 0 : getORDER_ID().hashCode());
        result = prime * result + ((getBWL_ID() == null) ? 0 : getBWL_ID().hashCode());
        result = prime * result + ((getSTATUS() == null) ? 0 : getSTATUS().hashCode());
        result = prime * result + ((getREMARKS() == null) ? 0 : getREMARKS().hashCode());
        result = prime * result + ((getSIGN() == null) ? 0 : getSIGN().hashCode());
        result = prime * result + ((getCREATED_ID() == null) ? 0 : getCREATED_ID().hashCode());
        result = prime * result + ((getCREATED_TIME() == null) ? 0 : getCREATED_TIME().hashCode());
        result = prime * result + ((getUPDATED_ID() == null) ? 0 : getUPDATED_ID().hashCode());
        result = prime * result + ((getUPDATED_TIME() == null) ? 0 : getUPDATED_TIME().hashCode());
        return result;
    }
}